export const ALLOWED_SETTINGS_GROUPS = [
  "company",
  "features",
  "employees",
  "outlets",
  "departments_positions",
  "payroll",
  "payroll_earnings",
  "leave",
  "long_leave",
  "holidays",
  "attendance",
  "roster",
  "assets_uniforms",
  "documents",
  "users_permissions",
  "approval_workflows",
  "approval_thresholds",
  "notifications",
  "reports",
  "offline_sync",
  "realtime_websocket",
  "import_export",
  "backup_recovery",
  "audit_security",
  "my_profile",
  "ui_preferences",
] as const;

export const APPROVAL_MODES = [
  "disabled",
  "manual",
  "auto_admin_superadmin",
  "full_workflow",
] as const;

export const PAYROLL_IMPACTING_GROUPS = new Set([
  "payroll",
  "payroll_earnings",
  "long_leave",
  "holidays",
]);

export const SENSITIVE_SETTING_GROUPS = new Set([
  "company",
  "features",
  "payroll",
  "payroll_earnings",
  "leave",
  "long_leave",
  "holidays",
  "attendance",
  "roster",
  "assets_uniforms",
  "documents",
  "users_permissions",
  "approval_workflows",
  "approval_thresholds",
  "offline_sync",
  "realtime_websocket",
  "import_export",
  "backup_recovery",
  "audit_security",
  "my_profile",
  "ui_preferences",
]);

export const FEATURE_DEPENDENCIES: Record<string, string[]> = {
  attendance: ["employee_management"],
  payslips: ["payroll"],
  long_leave: ["leave_management"],
  long_leave_management: ["leave_management"],
  offline_sync: ["attendance"],
  kiosk_attendance: ["attendance"],
  biometric_attendance: ["attendance"],
  employee_portal: ["employee_login"],
  employee_login: ["employee_management"],
  approval_workflows: ["approvals"],
  payroll: ["employee_management"],
  roster: ["employee_management"],
  documents: ["employee_management"],
  contract_tracking: ["employee_management"],
  assets_uniforms: ["employee_management"],
  asset_tracking: ["employee_management"],
  uniform_tracking: ["employee_management"],
};

export const FEATURE_DEPENDENCY_LABELS: Record<string, string> = {
  payroll: "Payroll Management",
  leave_management: "Leave Management",
  long_leave_management: "Long Leave Management",
  attendance: "Attendance Management",
  employee_login: "Employee Login",
  employee_management: "Employee Management",
  approvals: "Approvals",
  documents: "Document Tracking",
  asset_tracking: "Asset Tracking",
  uniform_tracking: "Uniform Tracking",
  roster: "Duty Roster",
  contract_tracking: "Contract Tracking",
  payslips: "Payslips",
  advance_salary: "Advance Salary",
};

export const MODULE_LIFECYCLE_METADATA: Record<string, {
  module_key: string;
  label: string;
  description: string;
  dependencies: string[];
  setup_activities: string[];
  disabled_by_choice: boolean;
  needs_setup_after_enable: boolean;
  review_recommended: boolean;
}> = {
  documents: {
    module_key: "documents",
    label: "Document Tracking",
    description: "Track employee documents, KYC records, expiries, and verification status.",
    dependencies: ["employee_management"],
    setup_activities: ["document_categories", "expiry_policy", "access_permissions"],
    disabled_by_choice: true,
    needs_setup_after_enable: true,
    review_recommended: true,
  },
  asset_tracking: {
    module_key: "asset_tracking",
    label: "Asset Tracking",
    description: "Track company assets assigned to employees, including issue, return, and history.",
    dependencies: ["employee_management"],
    setup_activities: ["asset_categories", "issue_return_policy", "asset_permissions"],
    disabled_by_choice: true,
    needs_setup_after_enable: true,
    review_recommended: true,
  },
  uniform_tracking: {
    module_key: "uniform_tracking",
    label: "Uniform Tracking",
    description: "Track uniforms issued to employees, including sizes, quantities, issue dates, and return status.",
    dependencies: ["employee_management"],
    setup_activities: ["uniform_catalog", "issue_return_policy", "uniform_permissions"],
    disabled_by_choice: true,
    needs_setup_after_enable: true,
    review_recommended: true,
  },
  leave_management: {
    module_key: "leave_management",
    label: "Leave Management",
    description: "Manage employee leave requests, balances, approvals, and leave history.",
    dependencies: ["employee_management"],
    setup_activities: ["leave_types", "leave_balances", "approval_workflow"],
    disabled_by_choice: true,
    needs_setup_after_enable: true,
    review_recommended: true,
  },
  long_leave_management: {
    module_key: "long_leave_management",
    label: "Long Leave Management",
    description: "Manage extended leave workflows, salary treatment, and long leave history.",
    dependencies: ["leave_management"],
    setup_activities: ["long_leave_policy", "payroll_deduction_review", "approval_workflow"],
    disabled_by_choice: true,
    needs_setup_after_enable: true,
    review_recommended: true,
  },
  roster: {
    module_key: "roster",
    label: "Duty Roster",
    description: "Plan employee work schedules, weekly duty rosters, shift assignments, and roster change workflows.",
    dependencies: ["employee_management"],
    setup_activities: ["shift_catalog", "roster_permissions", "approval_workflow"],
    disabled_by_choice: true,
    needs_setup_after_enable: true,
    review_recommended: true,
  },
  contract_tracking: {
    module_key: "contract_tracking",
    label: "Contract Tracking",
    description: "Track employee contracts, renewals, probation periods, linked documents, and expiry alerts.",
    dependencies: ["employee_management"],
    setup_activities: ["contract_rules", "expiry_alerts", "renewal_workflow"],
    disabled_by_choice: true,
    needs_setup_after_enable: true,
    review_recommended: true,
  },
  attendance: {
    module_key: "attendance",
    label: "Attendance Management",
    description: "Track employee attendance, lateness, absences, corrections, biometric/kiosk entries, and payroll review.",
    dependencies: ["employee_management"],
    setup_activities: ["time_rules", "sub_features", "devices", "correction_workflow"],
    disabled_by_choice: true,
    needs_setup_after_enable: true,
    review_recommended: true,
  },
  payroll: {
    module_key: "payroll",
    label: "Payroll Management",
    description: "Process salaries, payslips, advances, loans, overtime, benefits, deductions, and approvals.",
    dependencies: ["employee_management"],
    setup_activities: ["payroll_cycle", "salary_rules", "sub_features", "approval_workflow"],
    disabled_by_choice: true,
    needs_setup_after_enable: true,
    review_recommended: true,
  },
};

export const REPORTABLE_FEATURES = [
  "employee_management",
  "attendance",
  "leave_management",
  "long_leave_management",
  "payroll",
  "roster",
  "assets_uniforms",
  "asset_tracking",
  "uniform_tracking",
  "documents",
  "contract_tracking",
] as const;

type SettingsGroupKey = (typeof ALLOWED_SETTINGS_GROUPS)[number];

export const SETTINGS_GROUP_VIEW_PERMISSIONS: Record<
  SettingsGroupKey,
  readonly string[]
> = {
  company: ["company.view", "settings.view"],
  features: ["feature_settings.view", "settings.view"],
  employees: ["settings.view"],
  outlets: ["settings.view"],
  departments_positions: ["settings.view"],
  payroll: ["payroll_settings.view", "settings.view"],
  payroll_earnings: ["payroll_settings.view", "settings.view"],
  leave: ["leave_settings.view", "settings.view"],
  long_leave: ["leave_settings.view", "settings.view"],
  holidays: ["holiday_settings.view", "settings.view"],
  attendance: ["attendance.settings.view", "attendance_settings.view", "settings.view"],
  roster: ["roster_settings.manage", "settings.view"],
  assets_uniforms: ["assets_settings.manage", "settings.view"],
  documents: ["documents.settings.view", "documents_settings.manage", "settings.view"],
  users_permissions: ["security_settings.view", "settings.view"],
  approval_workflows: ["approval_workflows.view", "settings.view"],
  approval_thresholds: ["approval_thresholds.view", "settings.view"],
  notifications: ["notifications.settings.view", "settings.view"],
  reports: ["reports.settings.view", "settings.view"],
  offline_sync: ["sync_settings.view", "settings.view"],
  realtime_websocket: ["realtime_settings.view", "settings.view"],
  import_export: ["import_export.settings.view", "import_export_settings.view", "settings.view"],
  backup_recovery: ["backup_settings.view", "settings.view"],
  audit_security: ["security.view", "audit_settings.view", "settings.view"],
  my_profile: ["settings.view"],
  ui_preferences: ["settings.view"],
};

export const SETTINGS_GROUP_MANAGE_PERMISSIONS: Record<
  SettingsGroupKey,
  readonly string[]
> = {
  company: ["company.manage", "settings.manage"],
  features: ["feature_settings.manage", "settings.manage"],
  employees: ["settings.manage"],
  outlets: ["settings.manage"],
  departments_positions: ["settings.manage"],
  payroll: ["payroll.settings.manage", "payroll_settings.manage", "settings.manage"],
  payroll_earnings: ["payroll_settings.manage", "settings.manage"],
  leave: ["leave.settings.manage", "leave_settings.manage", "settings.manage"],
  long_leave: ["leave_settings.manage", "settings.manage"],
  holidays: ["holiday_settings.manage", "settings.manage"],
  attendance: ["attendance.settings.manage", "attendance_settings.manage", "settings.manage"],
  roster: ["roster_settings.manage", "settings.manage"],
  assets_uniforms: ["assets_settings.manage", "settings.manage"],
  documents: ["documents.settings.manage", "documents_settings.manage", "settings.manage"],
  users_permissions: ["security.manage", "security_settings.manage", "settings.manage"],
  approval_workflows: ["approval_workflows.manage", "settings.manage"],
  approval_thresholds: ["approval_thresholds.edit", "settings.manage"],
  notifications: ["notifications.settings.manage", "settings.manage"],
  reports: ["reports.settings.manage", "settings.manage"],
  offline_sync: ["sync_settings.manage", "settings.manage"],
  realtime_websocket: ["realtime_settings.manage", "settings.manage"],
  import_export: ["import_export.settings.manage", "import_export_settings.manage", "settings.manage"],
  backup_recovery: ["backup.settings.manage", "backup_settings.manage", "settings.manage"],
  audit_security: ["security.manage", "audit_settings.manage", "settings.manage"],
  my_profile: ["settings.manage"],
  ui_preferences: ["settings.manage"],
};
