import type { HrReportColumn, HrReportDefinition } from "./hr-reports.types";

const employeeBaseColumns: HrReportColumn[] = [
  { key: "employee_id", label: "Employee ID", data_type: "text", description: "Internal employee record ID.", filterable: true },
  { key: "employee_code", label: "Employee Code", data_type: "text", description: "Employee code.", sortable: true, filterable: true },
  { key: "employee_name", label: "Employee Name", data_type: "text", description: "Employee full name.", sortable: true, filterable: true },
  { key: "employee_type", label: "Employee Type", data_type: "status", description: "Local or foreign employee type.", filterable: true },
  { key: "outlet_name", label: "Outlet", data_type: "text", description: "Current outlet.", filterable: true },
  { key: "department_name", label: "Department", data_type: "text", description: "Current department.", filterable: true },
  { key: "position_name", label: "Position", data_type: "text", description: "Current position.", filterable: true },
  { key: "employment_status", label: "Employment Status", data_type: "status", description: "Current employment status.", filterable: true },
];

const c = (key: string, label: string, data_type: HrReportColumn["data_type"], description = label): HrReportColumn => ({
  key,
  label,
  data_type,
  description,
  sortable: ["text", "date", "number"].includes(data_type),
  filterable: ["text", "status", "date"].includes(data_type),
});

export const HR_REPORT_DEFINITIONS: HrReportDefinition[] = [
  {
    report_key: "employee-master",
    name: "Employee Master Report",
    description: "Current employee master data with compliance, contract, long-leave, and profile completeness indicators.",
    category: "employee",
    required_permission: "hr_reports.employee.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["employee_id", "outlet_id", "department_id", "position_id", "employee_type", "employment_status", "search", "include_archived"],
    columns: [...employeeBaseColumns, c("nationality", "Nationality", "text"), c("joined_at", "Join Date", "date"), c("document_compliance_status", "Document Compliance", "status"), c("active_contract_status", "Active Contract", "status"), c("expiry_alert_severity", "Expiry Alert", "status"), c("probation_status", "Probation", "status"), c("active_long_leave_status", "Long Leave", "status"), c("profile_completeness", "Profile Completeness", "status")],
    route: "/api/v1/hr-reports/employee-master",
    export_ready: true,
  },
  {
    report_key: "employee-status",
    name: "Employee Status Report",
    description: "Lifecycle/status breakdown for active, probation, leave, long leave, resigned, terminated, archived, and offboarding employees.",
    category: "employee",
    required_permission: "hr_reports.employee.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["outlet_id", "department_id", "employee_type", "employment_status", "include_archived"],
    columns: [c("employment_status", "Status", "status"), c("total_employees", "Employees", "number"), c("local_employees", "Local", "number"), c("foreign_employees", "Foreign", "number"), c("offboarding_in_progress", "Offboarding", "number")],
    route: "/api/v1/hr-reports/employee-status",
    export_ready: true,
  },
  {
    report_key: "local-foreign",
    name: "Local vs Foreign Employee Report",
    description: "Local/foreign counts, nationality breakdown, and foreign compliance gaps.",
    category: "employee",
    required_permission: "hr_reports.employee.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["outlet_id", "department_id", "employee_type", "nationality", "search"],
    columns: [c("employee_type", "Employee Type", "status"), c("nationality", "Nationality", "text"), c("total_employees", "Employees", "number"), c("missing_passport", "Missing Passport", "number"), c("missing_work_permit", "Missing Work Permit", "number"), c("expiring_documents", "Expiring Documents", "number"), c("compliance_severity", "Compliance Severity", "status")],
    route: "/api/v1/hr-reports/local-foreign",
    export_ready: true,
  },
  {
    report_key: "headcount",
    name: "Employee by Outlet / Department / Position Report",
    description: "Headcount by outlet, department, and position with active/inactive and local/foreign split.",
    category: "employee",
    required_permission: "hr_reports.employee.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["outlet_id", "department_id", "position_id", "employee_type", "from_date", "to_date"],
    columns: [c("grouping", "Grouping", "text"), c("group_name", "Group", "text"), c("headcount", "Headcount", "number"), c("active_count", "Active", "number"), c("inactive_count", "Inactive", "number"), c("local_count", "Local", "number"), c("foreign_count", "Foreign", "number"), c("new_joiners_count", "New Joiners", "number"), c("long_leave_count", "Long Leave", "number"), c("compliance_risk_count", "Compliance Risk", "number")],
    route: "/api/v1/hr-reports/headcount",
    export_ready: true,
  },
  {
    report_key: "new-joiners",
    name: "New Joiners Report",
    description: "Employees joined within the selected date range.",
    category: "employee",
    required_permission: "hr_reports.employee.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["from_date", "to_date", "outlet_id", "department_id", "employee_type", "search"],
    columns: [...employeeBaseColumns, c("joined_at", "Join Date", "date"), c("probation_end_date", "Probation End", "date"), c("onboarding_document_status", "Onboarding Documents", "status"), c("contract_status", "Contract", "status"), c("profile_completeness", "Profile Completeness", "status")],
    route: "/api/v1/hr-reports/new-joiners",
    export_ready: true,
  },
  {
    report_key: "probation",
    name: "Probation Report",
    description: "Probation employees, days remaining, overdue status, and action required.",
    category: "employee",
    required_permission: "hr_reports.employee.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["as_of_date", "outlet_id", "department_id", "probation_status", "search"],
    columns: [...employeeBaseColumns, c("probation_end_date", "Probation End", "date"), c("days_remaining", "Days Remaining", "number"), c("probation_status", "Probation Status", "status"), c("action_required", "Action Required", "boolean")],
    route: "/api/v1/hr-reports/probation",
    export_ready: true,
  },
  {
    report_key: "contracts",
    name: "Contract Report",
    description: "Contract status, expiry, missing contracts, and renewal due indicators.",
    category: "compliance",
    required_permission: "hr_reports.compliance.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["as_of_date", "outlet_id", "department_id", "contract_status", "expiry_status", "search"],
    columns: [...employeeBaseColumns, c("contract_number", "Contract Number", "text"), c("contract_type", "Contract Type", "text"), c("contract_status", "Contract Status", "status"), c("start_date", "Start Date", "date"), c("end_date", "End Date", "date"), c("renewal_due_status", "Renewal Due", "status")],
    route: "/api/v1/hr-reports/contracts",
    export_ready: true,
  },
  {
    report_key: "document-compliance",
    name: "Document Compliance Report",
    description: "Document compliance by employee with missing, expired, and expiring document indicators.",
    category: "documents",
    required_permission: "hr_reports.documents.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["outlet_id", "department_id", "document_status", "expiry_status", "employee_type", "search"],
    columns: [...employeeBaseColumns, c("required_documents_count", "Required", "number"), c("uploaded_documents", "Uploaded", "number"), c("missing_documents", "Missing", "number"), c("expired_documents", "Expired", "number"), c("expiring_documents", "Expiring", "number"), c("passport_expiry_date", "Passport Expiry", "date"), c("work_permit_expiry_date", "Work Permit Expiry", "date"), c("compliance_status", "Compliance Status", "status"), c("expiry_alert_status", "Expiry Alert", "status")],
    route: "/api/v1/hr-reports/document-compliance",
    export_ready: true,
  },
  {
    report_key: "foreign-compliance",
    name: "Foreign Employee Compliance Report",
    description: "Passport, visa/work permit, and expiry compliance for foreign employees.",
    category: "compliance",
    required_permission: "hr_reports.compliance.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["outlet_id", "department_id", "expiry_status", "compliance_status", "nationality", "search"],
    columns: [...employeeBaseColumns, c("nationality", "Nationality", "text"), c("passport_number_masked", "Passport No.", "text"), c("passport_expiry_date", "Passport Expiry", "date"), c("work_permit_number_masked", "Work Permit No.", "text"), c("work_permit_expiry_date", "Work Permit Expiry", "date"), c("days_until_next_expiry", "Days Until Expiry", "number"), c("compliance_severity", "Severity", "status"), c("expiry_alert_id", "Expiry Alert", "text")],
    route: "/api/v1/hr-reports/foreign-compliance",
    export_ready: true,
  },
  {
    report_key: "leave-balances",
    name: "Leave Balance Report",
    description: "Leave balance aggregates from the Phase 9A balance engine.",
    category: "leave",
    required_permission: "hr_reports.leave.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["outlet_id", "department_id", "employee_id", "leave_type_id", "year", "search"],
    columns: [...employeeBaseColumns.slice(0, 3), c("leave_type", "Leave Type", "text"), c("entitlement_days", "Entitlement", "number"), c("opening_balance", "Opening", "number"), c("accrued_days", "Accrued", "number"), c("used_days", "Used", "number"), c("pending_days", "Pending", "number"), c("adjusted_days", "Adjusted", "number"), c("carried_forward_days", "Carried Forward", "number"), c("expired_days", "Expired", "number"), c("available_days", "Available", "number"), c("negative_balance_warning", "Negative Warning", "boolean"), c("last_accrual_date", "Last Accrual", "date")],
    route: "/api/v1/hr-reports/leave-balances",
    export_ready: true,
  },
  {
    report_key: "leave-requests",
    name: "Leave Request Report",
    description: "Leave requests with approval state, holiday-adjusted duration, and safe reason summary.",
    category: "leave",
    required_permission: "hr_reports.leave.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["from_date", "to_date", "outlet_id", "department_id", "employee_id", "leave_type_id", "leave_status", "approval_status", "search"],
    columns: [...employeeBaseColumns.slice(0, 3), c("leave_type", "Leave Type", "text"), c("start_date", "Start", "date"), c("end_date", "End", "date"), c("requested_duration_days", "Requested Days", "number"), c("duration_days", "Deducted Duration", "number"), c("holiday_adjusted_duration", "Holiday Adjusted", "number"), c("status", "Status", "status"), c("approval_status", "Approval", "status"), c("current_step", "Current Step", "text"), c("balance_impact", "Balance Impact", "number"), c("reason_summary", "Reason", "text")],
    route: "/api/v1/hr-reports/leave-requests",
    export_ready: true,
  },
  {
    report_key: "long-leave",
    name: "Long Leave Report",
    description: "Long leave records with approval, payroll review status, return risk, and estimated deduction summary.",
    category: "long_leave",
    required_permission: "hr_reports.long_leave.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["from_date", "to_date", "outlet_id", "department_id", "employee_id", "long_leave_status", "approval_status", "search"],
    columns: [...employeeBaseColumns.slice(0, 4), c("start_date", "Start", "date"), c("end_date", "End", "date"), c("expected_return_date", "Expected Return", "date"), c("actual_return_date", "Actual Return", "date"), c("status", "Status", "status"), c("approval_status", "Approval", "status"), c("payroll_status", "Payroll Review", "status"), c("estimated_deduction", "Estimated Deduction", "number"), c("return_overdue", "Overdue", "boolean")],
    route: "/api/v1/hr-reports/long-leave",
    export_ready: true,
  },
  {
    report_key: "assets-uniforms",
    name: "Asset / Uniform Assignment Report",
    description: "Assigned assets and uniforms, return status, condition, and overdue return flags.",
    category: "assets",
    required_permission: "hr_reports.assets.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["outlet_id", "department_id", "employee_id", "asset_status", "search"],
    columns: [...employeeBaseColumns.slice(0, 6), c("assignment_type", "Type", "status"), c("item_name", "Item", "text"), c("issue_date", "Issue Date", "date"), c("due_return_date", "Due / Return Date", "date"), c("condition_status", "Condition", "text"), c("assignment_status", "Status", "status"), c("overdue_return", "Overdue", "boolean")],
    route: "/api/v1/hr-reports/assets-uniforms",
    export_ready: true,
  },
  {
    report_key: "compliance-summary",
    name: "HR Compliance Summary Report",
    description: "Consolidated compliance metrics for documents, contracts, probation, alerts, and long leave.",
    category: "summary",
    required_permission: "hr_reports.compliance.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["as_of_date", "outlet_id", "department_id"],
    columns: [c("metric", "Metric", "text"), c("count", "Count", "number"), c("severity", "Severity", "status"), c("description", "Description", "text")],
    route: "/api/v1/hr-reports/compliance-summary",
    export_ready: true,
  },
  {
    report_key: "lifecycle",
    name: "Employee Lifecycle / History Report",
    description: "Safe job, status, contract, long leave, and audit timeline summary.",
    category: "lifecycle",
    required_permission: "hr_reports.lifecycle.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["from_date", "to_date", "outlet_id", "department_id", "employee_id", "search"],
    columns: [...employeeBaseColumns.slice(0, 3), c("event_type", "Event Type", "status"), c("event_label", "Event", "text"), c("event_date", "Date", "date"), c("reason", "Reason", "text")],
    route: "/api/v1/hr-reports/lifecycle",
    export_ready: true,
  },
  {
    report_key: "employee-360-summary",
    name: "Employee 360 Summary Report",
    description: "Compact employee-wise risk summary across attendance, leave, documents, long leave, contract, probation, and alerts.",
    category: "summary",
    required_permission: "hr_reports.employee_360.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["outlet_id", "department_id", "employee_type", "employment_status", "search"],
    columns: [...employeeBaseColumns, c("attendance_risk", "Attendance Risk", "status"), c("leave_risk", "Leave Risk", "status"), c("document_risk", "Document Risk", "status"), c("long_leave_status", "Long Leave", "status"), c("contract_probation_status", "Contract / Probation", "status"), c("open_alerts", "Open Alerts", "number"), c("next_action_required", "Next Action", "text")],
    route: "/api/v1/hr-reports/employee-360-summary",
    export_ready: true,
  },
];

export const HR_REPORT_BY_KEY = new Map(HR_REPORT_DEFINITIONS.map((report) => [report.report_key, report]));
