import type { Permission } from "@/features/roles/roles.types";

// TODO: Enable live Users & Access API calls when backend /users, /roles, and /permissions routes are implemented.
export const USER_ACCESS_API_CONNECTED = false;

export const SEEDED_PERMISSION_FOUNDATION: Permission[] = [
  { permission_key: "employees.view", module: "employees", action: "view" },
  { permission_key: "employees.create", module: "employees", action: "create" },
  { permission_key: "employees.edit", module: "employees", action: "edit" },
  { permission_key: "employees.archive", module: "employees", action: "archive" },
  { permission_key: "employees.restore", module: "employees", action: "restore" },
  { permission_key: "employees.export", module: "employees", action: "export" },
  { permission_key: "employees.view_sensitive", module: "employees", action: "view sensitive" },
  { permission_key: "employees.manage_status", module: "employees", action: "manage status" },
  { permission_key: "employees.manage_outlet_assignment", module: "employees", action: "manage outlet assignment" },
  { permission_key: "outlets.view", module: "outlets", action: "view" },
  { permission_key: "outlets.create", module: "outlets", action: "create" },
  { permission_key: "outlets.edit", module: "outlets", action: "edit" },
  { permission_key: "outlets.enable_disable", module: "outlets", action: "enable/disable" },
  { permission_key: "departments.view", module: "departments", action: "view" },
  { permission_key: "departments.create", module: "departments", action: "create" },
  { permission_key: "departments.edit", module: "departments", action: "edit" },
  { permission_key: "positions.view", module: "positions", action: "view" },
  { permission_key: "positions.create", module: "positions", action: "create" },
  { permission_key: "positions.edit", module: "positions", action: "edit" },
  { permission_key: "users.view", module: "users/access", action: "view" },
  { permission_key: "users.create", module: "users/access", action: "create" },
  { permission_key: "users.edit", module: "users/access", action: "edit" },
  { permission_key: "users.disable", module: "users/access", action: "disable" },
  { permission_key: "users.enable", module: "users/access", action: "enable" },
  { permission_key: "users.reset_password", module: "users/access", action: "reset password" },
  { permission_key: "users.revoke_sessions", module: "users/access", action: "revoke sessions" },
  { permission_key: "roles.view", module: "users/access", action: "view roles" },
  { permission_key: "roles.create", module: "users/access", action: "create roles" },
  { permission_key: "roles.edit", module: "users/access", action: "edit roles" },
  { permission_key: "settings.view", module: "settings", action: "view" },
  { permission_key: "settings.manage", module: "settings", action: "manage" },
  { permission_key: "feature_settings.view", module: "settings", action: "view features" },
  { permission_key: "feature_settings.manage", module: "settings", action: "manage features" },
  { permission_key: "attendance.view", module: "attendance", action: "view" },
  { permission_key: "leave.view", module: "leave", action: "view" },
  { permission_key: "payroll.view", module: "payroll", action: "view" },
  { permission_key: "assets.view", module: "assets/uniforms", action: "view assets" },
  { permission_key: "uniforms.view", module: "assets/uniforms", action: "view uniforms" },
  { permission_key: "documents.view", module: "documents", action: "view" },
  { permission_key: "documents.view_sensitive", module: "documents", action: "view sensitive" },
  { permission_key: "approvals.view", module: "approvals", action: "view" },
  { permission_key: "reports.view", module: "reports", action: "view" },
  { permission_key: "export.view", module: "import/export", action: "view exports" },
  { permission_key: "import.view", module: "import/export", action: "view imports" },
  { permission_key: "backup.view", module: "backup/recovery", action: "view" },
  { permission_key: "audit_logs.view", module: "audit", action: "view" },
];
