export const frontendFoundationChecks = [
  "AppShell renders with a collapsible sidebar and persisted state.",
  "Navigation filters items by permission and feature flags.",
  "ProtectedRoute redirects unauthenticated users to login.",
  "PermissionGuard shows the professional denied state.",
  "ModuleRoute denies direct /payroll access without payroll.view.",
  "ModuleRoute denies direct /documents access without documents.view.",
  "ModuleRoute denies direct /approvals access without approvals.view.",
  "ModuleRoute denies direct /reports access without reports.view.",
  "Feature-disabled module routes show a professional unavailable or permission denied state.",
  "Super Admin users bypass module route permission checks.",
  "Every sidebar navigation item has a matching placeholder route.",
  "Kiosk Devices uses offline_sync because it calls backend /devices APIs; future /kiosk can use kiosk_attendance.",
  "Assets and Uniforms use assets_uniforms as the seeded feature key.",
  "Import / Export uses seeded export.view or import.view permissions.",
  "Navigation does not use attendance_kiosk, assets, uniforms, or export_jobs.view feature/permission keys.",
  "Login-time 2FA verifies the server-issued challenge through /auth/2fa/verify.",
  "Authenticated 2FA setup confirmation uses /me/2fa/confirm so login challenges and profile setup stay separate.",
  "Pending 2FA credentials are memory-only and never stored in localStorage or sessionStorage.",
  "Refreshing /2fa without pending credentials redirects to login.",
  "First-time setup redirects to /setup when setup_required is true.",
  "First-time setup sends bootstrap token only as an Authorization Bearer header.",
  "First-time setup never stores bootstrap token in localStorage or sessionStorage.",
  "First-time setup redirects to login after success and does not auto-login.",
  "First-time setup updates the bootstrap status cache to setup_required false after initialize succeeds.",
  "First-time setup success navigates to /login without bouncing back to /setup.",
  "Forgot password shows a generic success message without revealing whether an account exists.",
  "Reset password requires a strong password and clears the token after submission.",
  "Dashboard calls /reports/dashboard/summary and renders partial summary data safely.",
  "Dashboard remains an authenticated route and does not require reports.view at the route guard.",
  "Dashboard 403 or permission denial renders Dashboard summary is not available for your role.",
  "Dashboard 403 does not show the generic retry-only error state.",
  "Dashboard network errors still show Dashboard data could not be loaded with retry.",
  "Dashboard permission denial state does not expose sensitive data.",
  "Profile official fields render read-only and never show password hashes or tokens.",
  "Change password validates strength and clears fields after success.",
  "KYC update requires reason and at least one requested change.",
  "2FA setup secret is not stored and backup codes are one-time display only.",
  "User menu links to profile, security, and logout.",
  "Network errors show a friendly connection message.",
  "API client parses success responses and throws typed ApiError objects.",
  "DataTable renders rows, loading skeletons, and empty states.",
  "RowActions expose accessible labels for icon-only controls.",
  "StatusBadge maps known HRM statuses consistently.",
  "The theme is light-only and no dark mode toggle exists.",
] as const;

export type FrontendFoundationCheck = (typeof frontendFoundationChecks)[number];
