export const hrAdminModuleChecks = [
  "Employee list renders with backend pagination.",
  "Employee filters update URL query params and call the API with query params.",
  "Create Employee button is hidden without employees.create.",
  "Edit Employee action is hidden without employees.edit.",
  "Employee detail drawer does not show salary history without salary.view or payroll.view.",
  "Employee detail drawer does not show documents without documents.view.",
  "Employee empty state renders No employees found.",
  "Employee error state renders Employees could not be loaded.",
  "Users list never renders password_hash, tokens, TOTP secrets, backup codes, or reset tokens.",
  "Users & Access page renders without calling /api/v1/users while USER_ACCESS_API_CONNECTED is false.",
  "Roles tab renders without calling /api/v1/roles while USER_ACCESS_API_CONNECTED is false.",
  "Permission Matrix renders without calling /api/v1/permissions.",
  "No fake success message is shown for disabled Users & Access actions.",
  "Role assignment actions are disabled until backend role assignment endpoints are available.",
  "User status actions require confirmation and reason when backend endpoints are available.",
  "User without users.view cannot access Users & Access route.",
  "Roles tab loads roles when the backend roles endpoint is available.",
  "Permission matrix groups seeded permissions by module.",
  "Super Admin role is protected or read-only when backend rules require it.",
  "No unseeded permission key appears in frontend navigation config.",
  "Active permission matrix contains only backend seeded permissions.",
  "Outlets list loads with backend pagination.",
  "Outlet create form validates required name.",
  "Outlet edit action is hidden without outlets.edit.",
  "Outlet deactivate workflow is not faked without reason-required endpoint wiring.",
  "Departments list loads with backend pagination.",
  "Department filters are sent to the API.",
  "Department create/edit form validates name.",
  "Department row actions render accessible labels.",
  "Positions list loads with backend pagination.",
  "Position department filter is sent to the API.",
  "Position create/edit form validates name.",
  "Position row actions render accessible labels.",
  "Settings page renders Company, Features, Attendance, Leave, Payroll, Approvals, Documents, and Backup sections.",
  "Feature switches are disabled without feature_settings.manage or settings.manage.",
  "Feature setting changes require a reason.",
  "Toggling a feature opens the feature reason dialog.",
  "Cancelling the feature reason dialog does not update the feature.",
  "Confirming feature change without reason shows A reason is required for this action.",
  "Confirming feature change with reason calls the update feature API.",
  "Native browser prompt dialogs are not used for feature setting changes.",
  "Failed feature update keeps the previous switch value.",
  "Successful feature update invalidates the feature settings query.",
  "Backend validation errors are shown in user-friendly alerts.",
  "Employee documents endpoint does not return file_key.",
  "Super Admin employee documents response does not return file_key.",
  "Sensitive employee document file names are masked without documents.view_sensitive.",
  "Sensitive employee document file names are visible with documents.view_sensitive.",
  "Document download can still use file_key internally.",
  "No dark mode setting, dark mode toggle, next-themes, or theme switching appears.",
  "App shell and collapsible sidebar still build.",
  "Employees page still renders.",
  "Settings page still renders.",
  "Permission-aware actions hide or disable Add Employee, Edit User, and Settings switches.",
  "Table pages remain table-first and do not use bubble-heavy card grids.",
] as const;

export type HrAdminModuleCheck = (typeof hrAdminModuleChecks)[number];
