import { describe, it } from "vitest";

describe.todo("Prompt 21 Leave + Payroll frontend", () => {
  it.todo("Leave requests list uses backend pagination and supports approve/reject/cancel reason dialogs");
  it.todo("Long leave page shows month-by-month salary impact without exposing sensitive payroll internals");
  it.todo("Payroll page blocks lifecycle actions through permission-aware route guards and reason dialogs");
  it.todo("Payroll items and totals are displayed using integer minor-unit money formatting");
  it.todo("Payslip batch generation respects outlet scope and download uses the backend placeholder");
  it.todo("Advances and salary loans submit amounts as integer minor units");
  it.todo("Salary loan actions show locked-period friendly errors and never use window.prompt");
  it.todo("Leave, payroll, payslip, advance, and loan tables remain light-only shadcn/Tailwind UI");
  it.todo("User with only payroll.view does not see Recalculate, Approve, Lock, Request reopen, or Reopen actions");
  it.todo("User with payroll.approve sees Approve only when payroll run status allows it");
  it.todo("User with payroll.lock sees Lock only when payroll run status allows it");
  it.todo("Super Admin sees permission-gated payroll lifecycle actions");
  it.todo("Hidden payroll lifecycle actions cannot be triggered from row actions");
  it.todo("User with only payslips.view does not see or trigger download placeholder action");
  it.todo("User with payslips.download sees download placeholder action");
  it.todo("Payslip rows and details never expose file_key");
  it.todo("Salary loans frontend sends start_month only when populated");
  it.todo("Salary loans backend accepts start_month and applies it to rows and count queries");
  it.todo("Invalid salary loan start_month is rejected with a validation error");
  it.todo("Salary loan start_month filtering does not bypass outlet access");
  it.todo("Advances frontend sends date_from and date_to only when populated and resets page to 1");
  it.todo("Advances backend accepts date_from/date_to and applies them to rows and count queries");
  it.todo("Invalid advance date range is rejected with a validation error");
  it.todo("Advance date filtering does not bypass outlet access");
  it.todo("Advance request success uses Advance payment requested successfully.");
  it.todo("No stale Advance payment created successfully message remains in the request flow");
});
