import { describe, it } from "vitest";

describe.todo("Combined remaining UI completion", () => {
  it.todo("ReportsPage renders catalog, generate, HR, attendance, payroll, compliance, audit, devices, and template tabs");
  it.todo("reports.view-only user does not call employee, asset, attendance, or leave report endpoints");
  it.todo("attendance.view user can load attendance report while missing leave.view shows a role placeholder");
  it.todo("missing module report permission shows 'This report is not available for your role.' without generic 403 alerts");
  it.todo("Reports payroll tab does not query without payroll.view");
  it.todo("Reports audit tab does not query without audit_logs.view");
  it.todo("Compliance document summary, expiring documents, and missing documents use granular permission guards");
  it.todo("Unavailable compliance section shows a permission-aware placeholder");
  it.todo("Reports compliance data remains sanitized and never renders file_key, token, secret, or password_hash");
  it.todo("Report result table handles empty rows and dynamic row shapes");
  it.todo("ImportExportPage renders exports, imports, and templates according to permissions");
  it.todo("Export download is hidden without export.download and never exposes file_key");
  it.todo("Sensitive export creation requires reason and backend permission");
  it.todo("Sensitive export without reason is blocked client-side and does not call the API");
  it.todo("Import upload rejects HTML, SVG, and executable MIME types");
  it.todo("Import upload without reason shows 'A reason is required for this action.' and does not call the API");
  it.todo("Import upload clears selected file, reason, local errors, and generated content after success or close");
  it.todo("Import apply placeholder does not claim data was imported when applied=false");
  it.todo("BackupRecoveryPage renders status, backup jobs, retention, and restore tabs according to permissions");
  it.todo("Backup download is hidden without backup.download and only shown when file_ready is true");
  it.todo("Backup completed messaging is not shown for queued-only jobs");
  it.todo("Queued or processing backup create response shows backup job created message");
  it.todo("Backup & Recovery nav uses the same backup any-permission logic as the route guard");
  it.todo("Restore requests never claim destructive production restore was executed");
  it.todo("Retention policy update requires reason");
  it.todo("Template and notification foundations render without fake save/send actions");
  it.todo("No provider API secret fields are rendered");
  it.todo("No dark mode toggle, next-themes dependency, or theme switcher is introduced");
  it.todo("Tables retain horizontal overflow for small screens");
  it.todo("Row action buttons keep accessible labels");
  it.todo("Hidden unauthorized tabs do not call protected APIs");
});
