import { useEffect, useState } from "react";
import { FormError } from "@/components/feedback/FormError";
import { LoadingButton } from "@/components/forms/LoadingButton";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { ApprovalStep } from "./approvals.types";

export const ApprovalStepDialog = ({ step, open, loading, error, onOpenChange, onSubmit }: { step?: ApprovalStep | null; open: boolean; loading?: boolean; error?: string | null; onOpenChange: (open: boolean) => void; onSubmit: (payload: Partial<ApprovalStep> & { reason?: string }) => void }) => {
  const [payload, setPayload] = useState({ step_order: "1", step_name: "", required_role_key: "", required_permission_key: "", approval_type: "single", amount_min: "", amount_max: "", reason: "" });
  useEffect(() => { if (open) setPayload({ step_order: String(step?.step_order ?? 1), step_name: step?.step_name ?? "", required_role_key: step?.required_role_key ?? "", required_permission_key: step?.required_permission_key ?? "", approval_type: step?.approval_type ?? "single", amount_min: step?.amount_min ? String(step.amount_min) : "", amount_max: step?.amount_max ? String(step.amount_max) : "", reason: "" }); }, [step, open]);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{step ? "Edit step" : "Create step"}</DialogTitle></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><Label className="space-y-1 text-sm">Order<Input type="number" value={payload.step_order} onChange={(e) => setPayload((p) => ({ ...p, step_order: e.target.value }))} /></Label><Label className="space-y-1 text-sm">Step name<Input value={payload.step_name} onChange={(e) => setPayload((p) => ({ ...p, step_name: e.target.value }))} /></Label><Label className="space-y-1 text-sm">Role<Input value={payload.required_role_key} onChange={(e) => setPayload((p) => ({ ...p, required_role_key: e.target.value }))} /></Label><Label className="space-y-1 text-sm">Permission<Input value={payload.required_permission_key} onChange={(e) => setPayload((p) => ({ ...p, required_permission_key: e.target.value }))} /></Label><Label className="space-y-1 text-sm">Amount min<Input type="number" value={payload.amount_min} onChange={(e) => setPayload((p) => ({ ...p, amount_min: e.target.value }))} /></Label><Label className="space-y-1 text-sm">Amount max<Input type="number" value={payload.amount_max} onChange={(e) => setPayload((p) => ({ ...p, amount_max: e.target.value }))} /></Label></div><Textarea value={payload.reason} placeholder="Reason" onChange={(e) => setPayload((p) => ({ ...p, reason: e.target.value }))} /><FormError message={error ?? undefined} /><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><LoadingButton loading={loading} onClick={() => onSubmit({ step_order: Number(payload.step_order), step_name: payload.step_name, required_role_key: payload.required_role_key || null, required_permission_key: payload.required_permission_key || null, approval_type: payload.approval_type, amount_min: payload.amount_min ? Number(payload.amount_min) : null, amount_max: payload.amount_max ? Number(payload.amount_max) : null, reason: payload.reason })}>Save step</LoadingButton></DialogFooter></DialogContent></Dialog>;
};
