import { useEffect, useState } from "react";
import { FormError } from "@/components/feedback/FormError";
import { AppDatePicker } from "@/components/forms/AppDatePicker";
import { LoadingButton } from "@/components/forms/LoadingButton";
import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import type { ApprovalThreshold } from "./approvals.types";

export const ApprovalThresholdDialog = ({ threshold, open, loading, error, onOpenChange, onSubmit }: { threshold?: ApprovalThreshold | null; open: boolean; loading?: boolean; error?: string | null; onOpenChange: (open: boolean) => void; onSubmit: (payload: Partial<ApprovalThreshold> & { reason?: string }) => void }) => {
  const [payload, setPayload] = useState({ workflow_key: "", threshold_name: "", threshold_type: "", amount_min: "", amount_max: "", currency: "MVR", effective_from: "", reason: "" });
  useEffect(() => { if (open) setPayload({ workflow_key: threshold?.workflow_key ?? "", threshold_name: threshold?.threshold_name ?? "", threshold_type: threshold?.threshold_type ?? "", amount_min: threshold?.amount_min ? String(threshold.amount_min) : "", amount_max: threshold?.amount_max ? String(threshold.amount_max) : "", currency: threshold?.currency ?? "MVR", effective_from: threshold?.effective_from ?? "", reason: "" }); }, [threshold, open]);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{threshold ? "Edit threshold" : "Create threshold"}</DialogTitle></DialogHeader><div className="grid gap-3 sm:grid-cols-2"><Label className="space-y-1 text-sm">Workflow key<Input value={payload.workflow_key} onChange={(e) => setPayload((p) => ({ ...p, workflow_key: e.target.value }))} /></Label><Label className="space-y-1 text-sm">Name<Input value={payload.threshold_name} onChange={(e) => setPayload((p) => ({ ...p, threshold_name: e.target.value }))} /></Label><Label className="space-y-1 text-sm">Type<Input value={payload.threshold_type} onChange={(e) => setPayload((p) => ({ ...p, threshold_type: e.target.value }))} /></Label><Label className="space-y-1 text-sm">Currency<Input value={payload.currency} onChange={(e) => setPayload((p) => ({ ...p, currency: e.target.value }))} /></Label><Label className="space-y-1 text-sm">Amount min<Input type="number" value={payload.amount_min} onChange={(e) => setPayload((p) => ({ ...p, amount_min: e.target.value }))} /></Label><Label className="space-y-1 text-sm">Amount max<Input type="number" value={payload.amount_max} onChange={(e) => setPayload((p) => ({ ...p, amount_max: e.target.value }))} /></Label><AppDatePicker label="Effective from" value={payload.effective_from} onChange={(value) => setPayload((p) => ({ ...p, effective_from: value ?? "" }))} /></div><Textarea value={payload.reason} placeholder="Reason" onChange={(e) => setPayload((p) => ({ ...p, reason: e.target.value }))} /><FormError message={error ?? undefined} /><DialogFooter><Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button><LoadingButton loading={loading} onClick={() => onSubmit({ workflow_key: payload.workflow_key, threshold_name: payload.threshold_name, threshold_type: payload.threshold_type, amount_min: payload.amount_min ? Number(payload.amount_min) : null, amount_max: payload.amount_max ? Number(payload.amount_max) : null, currency: payload.currency, effective_from: payload.effective_from || null, reason: payload.reason })}>Save threshold</LoadingButton></DialogFooter></DialogContent></Dialog>;
};
