export const MODULE_FEATURE_ALIASES: Record<string, string[]> = {
  employees: ["employees", "employee_management"],
  employee_structure: ["employee_structure", "employee_management"],
  employee_login: ["employee_login", "employee_management", "user_management"],
  approvals: ["approvals"],
  operation_ownership: ["operation_ownership"],
  leave: ["leave", "leave_management"],
  attendance: ["attendance"],
  roster: ["roster"],
  payroll: ["payroll"],
  payroll_adjustments: ["payroll_adjustments"],
  advance_salary: ["advance_salary"],
  payslips: ["payslips"],
  documents_kyc: ["documents_kyc", "documents", "kyc_update_requests"],
  document_tracking: ["documents"],
  asset_tracking: ["asset_tracking"],
  uniform_tracking: ["uniform_tracking"],
  assets_uniforms: ["assets_uniforms", "asset_tracking", "uniform_tracking"],
  employee_structure_changes: ["employee_structure_changes"],
  resignation_offboarding: ["resignation_offboarding", "employee_lifecycle"],
  disciplinary_actions: ["disciplinary_actions", "employee_discipline"],
  biometric: ["biometric", "biometric_attendance"],
  kiosk: ["kiosk", "offline_sync", "kiosk_attendance"],
  reports: ["reports"],
  settings: ["settings"],
  audit: ["audit", "audit_logs"],
};

export const resolveModuleFeatureAliases = (featureKey: string): string[] =>
  MODULE_FEATURE_ALIASES[featureKey] ?? [featureKey];
