import type { PayrollReportColumn, PayrollReportDefinition } from "./payroll-reports.types";

const employeeBaseColumns: PayrollReportColumn[] = [
  { key: "employee_id", label: "Employee ID", data_type: "text", description: "Internal employee record ID.", filterable: true },
  { key: "employee_code", label: "Employee Code", data_type: "text", description: "Employee code.", sortable: true, filterable: true },
  { key: "employee_name", label: "Employee Name", data_type: "text", description: "Employee full name.", sortable: true, filterable: true },
  { key: "outlet_name", label: "Outlet", data_type: "text", description: "Current outlet.", filterable: true },
  { key: "department_name", label: "Department", data_type: "text", description: "Current department.", filterable: true },
  { key: "position_name", label: "Position", data_type: "text", description: "Current position.", filterable: true },
];

const c = (
  key: string,
  label: string,
  data_type: PayrollReportColumn["data_type"],
  description = label,
  sensitive = data_type === "money",
): PayrollReportColumn => ({
  key,
  label,
  data_type,
  description,
  sortable: ["text", "date", "number", "money"].includes(data_type),
  filterable: ["text", "status", "date"].includes(data_type),
  sensitive,
});

const month = c("payroll_month", "Payroll Month", "text", "Payroll month.");
const run = c("payroll_run_id", "Payroll Run", "text", "Payroll run reference.");
const status = c("payroll_status", "Payroll Status", "status", "Payroll run or item status.", false);
const gross = c("gross_salary", "Gross Salary", "money");
const deductions = c("total_deductions", "Deductions", "money");
const net = c("net_payable_salary", "Net Payable", "money");

export const PAYROLL_REPORT_DEFINITIONS: PayrollReportDefinition[] = [
  {
    report_key: "monthly-summary",
    name: "Monthly Payroll Summary Report",
    description: "Payroll run totals, approval/finalization state, payslip warnings, and payroll cost summary by month.",
    category: "payroll",
    required_permission: "payroll_reports.summary.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["payroll_month", "payroll_run_id", "from_date", "to_date", "payroll_status", "outlet_id"],
    columns: [month, run, status, c("total_employees", "Employees", "number", "Employees included.", false), c("total_gross_salary", "Gross Salary", "money"), c("total_allowances", "Allowances", "money"), deductions, c("total_advances_deducted", "Advances", "money"), c("total_salary_loan_deductions", "Loans", "money"), c("total_attendance_deductions", "Attendance Deductions", "money"), c("total_long_leave_deductions", "Long Leave Deductions", "money"), c("total_overtime_amount", "Overtime", "money"), net, c("finalized_at", "Finalized", "date", "Finalized date.", false), c("warnings_count", "Warnings", "number", "Open payroll warnings.", false)],
    route: "/api/v1/payroll-reports/monthly-summary",
    export_ready: true,
    sensitive: true,
  },
  {
    report_key: "employee-detail",
    name: "Employee Payroll Detail Report",
    description: "Employee-level payroll amounts, deduction breakdowns, payslip status, and payroll warnings.",
    category: "payroll",
    required_permission: "payroll_reports.employee.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["payroll_month", "payroll_run_id", "employee_id", "outlet_id", "department_id", "payroll_status", "payslip_status", "search"],
    columns: [...employeeBaseColumns, month, run, c("base_salary", "Base Salary", "money"), gross, c("allowances", "Allowances", "money"), c("overtime_amount", "Overtime", "money"), deductions, c("advance_deduction", "Advance", "money"), c("loan_deduction", "Loan", "money"), c("attendance_deduction", "Attendance", "money"), c("long_leave_deduction", "Long Leave", "money"), c("unpaid_leave_deduction", "Unpaid Leave", "money"), net, status, c("payslip_status", "Payslip", "status", "Payslip status.", false), c("payment_method_summary", "Payment Method", "text", "Masked payment method.", true), c("warnings_count", "Warnings", "number", "Payroll warnings.", false)],
    route: "/api/v1/payroll-reports/employee-detail",
    export_ready: true,
    sensitive: true,
  },
  {
    report_key: "salary-compensation",
    name: "Salary / Compensation Report",
    description: "Current salary setup and recurring compensation component summary.",
    category: "salary",
    required_permission: "payroll_reports.salary.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["employee_id", "outlet_id", "department_id", "component_type", "search"],
    columns: [...employeeBaseColumns, c("base_salary", "Base Salary", "money"), c("salary_effective_date", "Effective Date", "date", "Current salary effective date.", false), c("salary_status", "Salary Status", "status", "Salary timeline status.", false), c("last_salary_change", "Last Change", "date", "Last salary change date.", false), c("pending_salary_change", "Pending Change", "status", "Pending salary approval.", false), c("compensation_component_summary", "Components", "text", "Recurring compensation component summary.", true)],
    route: "/api/v1/payroll-reports/salary-compensation",
    export_ready: true,
    sensitive: true,
  },
  {
    report_key: "salary-changes",
    name: "Salary Change / Increment History Report",
    description: "Salary change timeline with old/new salary, effective dates, status, and safe approval reference.",
    category: "salary",
    required_permission: "payroll_reports.salary.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["from_date", "to_date", "employee_id", "outlet_id", "department_id", "search"],
    columns: [...employeeBaseColumns.slice(0, 3), c("old_salary", "Old Salary", "money"), c("new_salary", "New Salary", "money"), c("effective_date", "Effective Date", "date", "Salary effective date.", false), c("change_reason", "Reason", "text", "Safe reason summary.", false), c("approved_by", "Approved By", "text", "Approval actor.", false), c("created_by", "Created By", "text", "Creator.", false), c("status", "Status", "status", "Change status.", false), c("audit_reference", "Audit Ref", "text", "Safe audit reference.", false)],
    route: "/api/v1/payroll-reports/salary-changes",
    export_ready: true,
    sensitive: true,
  },
  {
    report_key: "deductions",
    name: "Deductions Report",
    description: "Payroll deductions by type and source reference.",
    category: "deductions",
    required_permission: "payroll_reports.deductions.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["payroll_month", "from_date", "to_date", "employee_id", "outlet_id", "deduction_type", "search"],
    columns: [...employeeBaseColumns.slice(0, 5), month, c("deduction_type", "Type", "status", "Deduction type.", false), c("deduction_source", "Source", "status", "Deduction source.", false), c("deduction_amount", "Amount", "money"), c("status", "Status", "status", "Payroll item status.", false), c("source_reference", "Source Ref", "text", "Safe source reference.", false), c("reason", "Reason", "text", "Reason summary.", false), c("created_at", "Created", "date", "Created date.", false)],
    route: "/api/v1/payroll-reports/deductions",
    export_ready: true,
    sensitive: true,
  },
  {
    report_key: "advances",
    name: "Advance Payment Report",
    description: "Advance payments, deduction month, repaid amount, remaining balance, and approval status.",
    category: "advances_loans",
    required_permission: "payroll_reports.advances.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["payroll_month", "from_date", "to_date", "employee_id", "outlet_id", "payment_status", "search"],
    columns: [...employeeBaseColumns.slice(0, 5), c("advance_amount", "Advance Amount", "money"), c("advance_date", "Advance Date", "date", "Paid date.", false), c("payroll_deduction_month", "Deduction Month", "text", "Scheduled deduction month.", false), c("deducted_amount", "Deducted", "money"), c("remaining_balance", "Remaining", "money"), c("approval_status", "Approval", "status", "Approval status.", false), c("reason", "Reason", "text", "Reason summary.", false), c("created_by", "Created By", "text", "Creator.", false)],
    route: "/api/v1/payroll-reports/advances",
    export_ready: true,
    sensitive: true,
  },
  {
    report_key: "salary-loans",
    name: "Salary Loan Report",
    description: "Salary loans, installment amounts, deductions, outstanding balance, and loan status.",
    category: "advances_loans",
    required_permission: "payroll_reports.loans.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["payroll_month", "employee_id", "outlet_id", "payment_status", "search"],
    columns: [...employeeBaseColumns.slice(0, 5), c("loan_amount", "Loan Amount", "money"), c("installment_amount", "Installment", "money"), c("paid_this_month", "Paid This Month", "money"), c("total_paid_to_date", "Total Paid To Date", "money"), c("remaining_balance", "Remaining", "money"), month, c("loan_status", "Loan Status", "status", "Loan status.", false), c("start_date", "Start Month", "text", "Loan start month.", false), c("end_date", "End Month", "text", "Last installment month.", false), c("approval_status", "Approval", "status", "Approval status.", false)],
    route: "/api/v1/payroll-reports/salary-loans",
    export_ready: true,
    sensitive: true,
  },
  {
    report_key: "attendance-deductions",
    name: "Attendance Deduction Report",
    description: "Attendance summary and payroll deduction context for missing punches, absences, and payroll-impacting exceptions.",
    category: "attendance",
    required_permission: "payroll_reports.attendance_deductions.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["payroll_month", "from_date", "to_date", "employee_id", "outlet_id", "department_id", "search"],
    columns: [...employeeBaseColumns.slice(0, 5), month, c("absent_days", "Absent Days", "number", "Absent days.", false), c("unpaid_leave_days", "Unpaid Leave Days", "number", "Unpaid leave days.", false), c("missing_punch_days", "Missing Punch Days", "number", "Missing punch days.", false), c("attendance_deduction_amount", "Deduction", "money"), c("attendance_exception_warnings", "Warnings", "number", "Exception warnings.", false), status],
    route: "/api/v1/payroll-reports/attendance-deductions",
    export_ready: true,
    sensitive: true,
  },
  {
    report_key: "overtime",
    name: "Overtime Report",
    description: "Overtime minutes/hours, holiday work indicator, approval status where available, and overtime amount.",
    category: "attendance",
    required_permission: "payroll_reports.overtime.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["payroll_month", "from_date", "to_date", "employee_id", "outlet_id", "department_id", "search"],
    columns: [...employeeBaseColumns.slice(0, 5), month, c("overtime_minutes", "Overtime Minutes", "number", "Overtime minutes.", false), c("overtime_hours", "Overtime Hours", "number", "Overtime hours.", false), c("approval_status", "Approval", "status", "Approval status.", false), c("overtime_amount", "Amount", "money"), c("holiday_overtime", "Holiday OT", "boolean", "Holiday overtime indicator.", false)],
    route: "/api/v1/payroll-reports/overtime",
    export_ready: true,
    sensitive: true,
  },
  {
    report_key: "long-leave-deductions",
    name: "Long Leave Deduction Report",
    description: "Phase 9C long leave payroll impacts by month.",
    category: "long_leave",
    required_permission: "payroll_reports.long_leave.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["payroll_month", "from_date", "to_date", "employee_id", "outlet_id", "long_leave_status", "search"],
    columns: [...employeeBaseColumns.slice(0, 5), c("long_leave_id", "Long Leave", "text", "Long leave reference.", false), month, c("start_date", "Start", "date", "Start date.", false), c("end_date", "End", "date", "Expected return/end date.", false), c("total_days", "Total Days", "number", "Period total days.", false), c("long_leave_days", "Long Leave Days", "number", "Long leave days.", false), c("payable_days", "Payable Days", "number", "Payable days.", false), c("unpaid_days", "Unpaid Days", "number", "Unpaid days.", false), c("holiday_days", "Holiday Days", "number", "Holiday days.", false), c("payable_holiday_days", "Payable Holidays", "number", "Payable holiday days.", false), c("deduction_amount", "Deduction", "money"), c("payable_salary", "Payable Salary", "money"), c("payroll_review_status", "Payroll Review", "status", "Payroll review status.", false)],
    route: "/api/v1/payroll-reports/long-leave-deductions",
    export_ready: true,
    sensitive: true,
  },
  {
    report_key: "leave-deductions",
    name: "Leave Deduction / Unpaid Leave Report",
    description: "Unpaid leave and leave-related payroll deduction context.",
    category: "deductions",
    required_permission: "payroll_reports.leave_deductions.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["payroll_month", "from_date", "to_date", "employee_id", "outlet_id", "leave_status", "search"],
    columns: [...employeeBaseColumns.slice(0, 5), c("leave_type", "Leave Type", "text", "Leave type.", false), c("leave_request_id", "Leave Request", "text", "Leave request reference.", false), month, c("unpaid_leave_days", "Unpaid Days", "number", "Unpaid leave days.", false), c("paid_leave_days", "Paid Days", "number", "Paid leave days.", false), c("holiday_adjusted_duration", "Holiday Adjusted", "number", "Holiday-adjusted duration.", false), c("deduction_amount", "Deduction", "money"), c("approval_status", "Approval", "status", "Approval status.", false), status],
    route: "/api/v1/payroll-reports/leave-deductions",
    export_ready: true,
    sensitive: true,
  },
  {
    report_key: "payslip-status",
    name: "Payslip Status Report",
    description: "Payslip generated/missing status by employee and payroll run.",
    category: "payslips",
    required_permission: "payroll_reports.payslips.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["payroll_month", "payroll_run_id", "employee_id", "outlet_id", "payslip_status", "search"],
    columns: [...employeeBaseColumns.slice(0, 5), month, run, c("payslip_generated", "Generated", "boolean", "Payslip generated.", false), c("payslip_generated_at", "Generated At", "date", "Generated timestamp.", false), c("payslip_generated_by", "Generated By", "text", "Generated by.", false), c("payslip_status", "Payslip Status", "status", "Payslip status.", false), c("locked_finalized", "Locked", "boolean", "Payroll finalized/locked indicator.", false), c("missing_finalized_warning", "Missing Warning", "boolean", "Finalized payroll missing payslip.", false)],
    route: "/api/v1/payroll-reports/payslip-status",
    export_ready: true,
    sensitive: false,
  },
  {
    report_key: "approval-finalization",
    name: "Payroll Approval / Finalization Report",
    description: "Payroll approval, finalization, lock status, and pending approval counts.",
    category: "approvals",
    required_permission: "payroll_reports.approvals.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["payroll_month", "payroll_run_id", "payroll_status", "approval_status"],
    columns: [month, run, c("approval_status", "Approval", "status", "Approval status.", false), c("approval_steps", "Steps", "number", "Approval steps.", false), c("approved_by", "Approved By", "text", "Approved by.", false), c("rejected_by", "Rejected By", "text", "Rejected by.", false), c("finalized_by", "Finalized By", "text", "Finalized by.", false), c("finalized_date", "Finalized", "date", "Finalized date.", false), c("locked_status", "Locked Status", "status", "Locked/finalized status.", false), c("pending_approval_count", "Pending", "number", "Pending approval count.", false)],
    route: "/api/v1/payroll-reports/approval-finalization",
    export_ready: true,
    sensitive: false,
  },
  {
    report_key: "outlet-cost",
    name: "Outlet Payroll Cost Report",
    description: "Payroll cost grouped by outlet.",
    category: "cost",
    required_permission: "payroll_reports.cost.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["payroll_month", "from_date", "to_date", "outlet_id", "payroll_status"],
    columns: [c("grouping", "Grouping", "text", "Grouping type.", false), c("group_id", "Group ID", "text", "Outlet ID.", false), c("group_name", "Outlet", "text", "Outlet name.", false), c("employee_count", "Employees", "number", "Employee count.", false), gross, c("allowances_total", "Allowances", "money"), deductions, c("overtime_total", "Overtime", "money"), c("long_leave_deductions_total", "Long Leave Deductions", "money"), net, month, status],
    route: "/api/v1/payroll-reports/outlet-cost",
    export_ready: true,
    sensitive: true,
  },
  {
    report_key: "department-cost",
    name: "Department Payroll Cost Report",
    description: "Payroll cost grouped by department.",
    category: "cost",
    required_permission: "payroll_reports.cost.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["payroll_month", "from_date", "to_date", "outlet_id", "department_id", "payroll_status"],
    columns: [c("grouping", "Grouping", "text", "Grouping type.", false), c("group_id", "Group ID", "text", "Department ID.", false), c("group_name", "Department", "text", "Department name.", false), c("employee_count", "Employees", "number", "Employee count.", false), gross, c("allowances_total", "Allowances", "money"), deductions, c("overtime_total", "Overtime", "money"), c("long_leave_deductions_total", "Long Leave Deductions", "money"), net, month, status],
    route: "/api/v1/payroll-reports/department-cost",
    export_ready: true,
    sensitive: true,
  },
  {
    report_key: "variance",
    name: "Payroll Variance Report",
    description: "Current versus previous payroll amount variance by employee.",
    category: "cost",
    required_permission: "payroll_reports.variance.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["payroll_month", "employee_id", "outlet_id", "department_id", "variance_threshold", "search"],
    columns: [...employeeBaseColumns.slice(0, 5), month, c("current_gross", "Current Gross", "money"), c("previous_gross", "Previous Gross", "money"), c("current_net", "Current Net", "money"), c("previous_net", "Previous Net", "money"), c("difference_amount", "Difference", "money"), c("difference_percent", "Difference %", "number", "Variance percentage.", false), c("variance_reason", "Reason", "text", "Identified reason.", false)],
    route: "/api/v1/payroll-reports/variance",
    export_ready: true,
    sensitive: true,
  },
  {
    report_key: "audit",
    name: "Payroll Audit Report",
    description: "Safe payroll audit trail without raw metadata.",
    category: "audit",
    required_permission: "payroll_reports.audit.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["from_date", "to_date", "payroll_run_id", "employee_id", "search"],
    columns: [run, c("employee_id", "Employee", "text", "Employee reference.", false), c("action", "Action", "text", "Audit action.", false), c("actor", "Actor", "text", "Actor user.", false), c("timestamp", "Timestamp", "date", "Event timestamp.", false), c("before_after_summary", "Summary", "text", "Safe before/after summary.", false), c("reason", "Reason", "text", "Reason.", false), c("entity_reference", "Entity Ref", "text", "Entity reference.", false)],
    route: "/api/v1/payroll-reports/audit",
    export_ready: true,
    sensitive: false,
  },
  {
    report_key: "finance-summary",
    name: "Finance Summary Report",
    description: "Finance-facing payroll totals and payment status summary without ledger posting.",
    category: "finance_summary",
    required_permission: "payroll_reports.finance_summary.view",
    default_filters: { page: 1, page_size: 25 },
    available_filters: ["payroll_month", "from_date", "to_date", "outlet_id", "department_id", "payment_status"],
    columns: [month, c("grouping", "Grouping", "text", "Outlet/department grouping.", false), c("group_name", "Group", "text", "Group name.", false), c("gross_payroll", "Gross Payroll", "money"), c("net_payable", "Net Payable", "money"), c("deductions_total", "Deductions", "money"), c("advances_recovered", "Advances Recovered", "money"), c("loans_recovered", "Loans Recovered", "money"), c("overtime_total", "Overtime", "money"), c("employer_cost", "Employer Cost", "money"), c("payment_status", "Payment Status", "status", "Payment status.", false)],
    route: "/api/v1/payroll-reports/finance-summary",
    export_ready: true,
    sensitive: true,
  },
];

export const PAYROLL_REPORT_BY_KEY = new Map(PAYROLL_REPORT_DEFINITIONS.map((report) => [report.report_key, report]));
