INSERT OR IGNORE INTO permissions (id, permission_key, module, action, description, created_at) VALUES
('perm_employees_view', 'employees.view', 'employees', 'view', 'View employee list and employee profiles.', '2026-01-01T00:00:00Z'),
('perm_employees_profile_view', 'employees.profile.view', 'employees', 'profile_view', 'View employee profile lookup and profile selector data.', '2026-01-01T00:00:00Z'),
('perm_employees_create', 'employees.create', 'employees', 'create', 'Create employee records.', '2026-01-01T00:00:00Z'),
('perm_employees_edit', 'employees.edit', 'employees', 'edit', 'Edit employee records.', '2026-01-01T00:00:00Z'),
('perm_employees_archive', 'employees.archive', 'employees', 'archive', 'Archive employee records.', '2026-01-01T00:00:00Z'),
('perm_employees_restore', 'employees.restore', 'employees', 'restore', 'Restore archived employee records.', '2026-01-01T00:00:00Z'),
('perm_employees_export', 'employees.export', 'employees', 'export', 'Export employee lists and reports.', '2026-01-01T00:00:00Z'),
('perm_employees_view_sensitive', 'employees.view_sensitive', 'employees', 'view_sensitive', 'View sensitive employee information.', '2026-01-01T00:00:00Z'),
('perm_employees_login_view', 'employees.login.view', 'employees', 'login_view', 'View employee login assignment status.', '2026-01-01T00:00:00Z'),
('perm_employees_login_create', 'employees.login.create', 'employees', 'login_create', 'Create login access for an existing employee.', '2026-01-01T00:00:00Z'),
('perm_employees_login_link', 'employees.login.link', 'employees', 'login_link', 'Link an existing user to an employee.', '2026-01-01T00:00:00Z'),
('perm_employees_login_revoke', 'employees.login.revoke', 'employees', 'login_revoke', 'Deactivate or revoke employee login access.', '2026-01-01T00:00:00Z'),
('perm_employees_manage_status', 'employees.manage_status', 'employees', 'manage_status', 'Change employee employment status.', '2026-01-01T00:00:00Z'),
('perm_employees_manage_outlet_assignment', 'employees.manage_outlet_assignment', 'employees', 'manage_outlet_assignment', 'Manage employee outlet assignments.', '2026-01-01T00:00:00Z'),
('perm_employees_offboarding_view', 'employees.offboarding.view', 'employees', 'offboarding_view', 'View employee offboarding cases and checklist status.', '2026-01-01T00:00:00Z'),
('perm_employees_offboarding_manage', 'employees.offboarding.manage', 'employees', 'offboarding_manage', 'Start, update, cancel, and complete employee offboarding cases.', '2026-01-01T00:00:00Z'),
('perm_employees_offboarding_complete_task', 'employees.offboarding.complete_task', 'employees', 'offboarding_complete_task', 'Complete or waive employee offboarding checklist tasks.', '2026-01-01T00:00:00Z'),
('perm_employees_offboarding_final_settlement', 'employees.offboarding.final_settlement', 'employees', 'offboarding_final_settlement', 'Prepare employee final settlement drafts for payroll review.', '2026-01-01T00:00:00Z'),
('perm_employees_contracts_view', 'employees.contracts.view', 'employees', 'contracts_view', 'View employee contracts, expiry warnings, and contract history.', '2026-01-01T00:00:00Z'),
('perm_employees_contracts_manage', 'employees.contracts.manage', 'employees', 'contracts_manage', 'Create, update, renew, archive, and link employee contracts.', '2026-01-01T00:00:00Z'),
('perm_contracts_view', 'contracts.view', 'contracts', 'view', 'View company employee contract records.', '2026-01-01T00:00:00Z'),
('perm_contracts_manage', 'contracts.manage', 'contracts', 'manage', 'Manage company employee contract records.', '2026-01-01T00:00:00Z'),
('perm_my_profile_view', 'my_profile.view', 'my_profile', 'view', 'View own profile page.', '2026-01-01T00:00:00Z'),
('perm_my_profile_change_password', 'my_profile.change_password', 'my_profile', 'change_password', 'Change own password.', '2026-01-01T00:00:00Z'),
('perm_my_profile_manage_own_2fa', 'my_profile.manage_own_2fa', 'my_profile', 'manage_own_2fa', 'Manage own two-factor authentication.', '2026-01-01T00:00:00Z'),
('perm_my_profile_submit_kyc_update', 'my_profile.submit_kyc_update', 'my_profile', 'submit_kyc_update', 'Submit own profile or KYC update request.', '2026-01-01T00:00:00Z'),
('perm_my_profile_view_activity', 'my_profile.view_activity', 'my_profile', 'view_activity', 'View own account activity.', '2026-01-01T00:00:00Z'),
('perm_auth_sessions_view_own', 'auth.sessions.view_own', 'my_profile', 'sessions_view_own', 'View own active browser sessions.', '2026-01-01T00:00:00Z'),
('perm_auth_sessions_revoke_own', 'auth.sessions.revoke_own', 'my_profile', 'sessions_revoke_own', 'Revoke own active browser sessions.', '2026-01-01T00:00:00Z'),
('perm_profile_update_requests_view', 'profile_update_requests.view', 'profile_update_requests', 'view', 'View profile update requests.', '2026-01-01T00:00:00Z'),
('perm_profile_update_requests_approve', 'profile_update_requests.approve', 'profile_update_requests', 'approve', 'Approve profile update requests.', '2026-01-01T00:00:00Z'),
('perm_profile_update_requests_reject', 'profile_update_requests.reject', 'profile_update_requests', 'reject', 'Reject profile update requests.', '2026-01-01T00:00:00Z'),
('perm_profile_update_requests_return_for_more_info', 'profile_update_requests.return_for_more_info', 'profile_update_requests', 'return_for_more_info', 'Return profile update requests for more information.', '2026-01-01T00:00:00Z'),
('perm_outlets_view', 'outlets.view', 'outlets', 'view', 'View outlets.', '2026-01-01T00:00:00Z'),
('perm_outlets_create', 'outlets.create', 'outlets', 'create', 'Create outlets.', '2026-01-01T00:00:00Z'),
('perm_outlets_edit', 'outlets.edit', 'outlets', 'edit', 'Edit outlets.', '2026-01-01T00:00:00Z'),
('perm_outlets_enable_disable', 'outlets.enable_disable', 'outlets', 'enable_disable', 'Enable or disable outlets.', '2026-01-01T00:00:00Z'),
('perm_departments_view', 'departments.view', 'departments', 'view', 'View departments.', '2026-01-01T00:00:00Z'),
('perm_departments_create', 'departments.create', 'departments', 'create', 'Create departments.', '2026-01-01T00:00:00Z'),
('perm_departments_edit', 'departments.edit', 'departments', 'edit', 'Edit departments.', '2026-01-01T00:00:00Z'),
('perm_departments_delete', 'departments.delete', 'departments', 'delete', 'Delete departments.', '2026-01-01T00:00:00Z'),
('perm_positions_view', 'positions.view', 'positions', 'view', 'View positions.', '2026-01-01T00:00:00Z'),
('perm_positions_create', 'positions.create', 'positions', 'create', 'Create positions.', '2026-01-01T00:00:00Z'),
('perm_positions_edit', 'positions.edit', 'positions', 'edit', 'Edit positions.', '2026-01-01T00:00:00Z'),
('perm_positions_delete', 'positions.delete', 'positions', 'delete', 'Delete positions.', '2026-01-01T00:00:00Z'),
('perm_attendance_view', 'attendance.view', 'attendance', 'view', 'View attendance records.', '2026-01-01T00:00:00Z'),
('perm_attendance_create', 'attendance.create', 'attendance', 'create', 'Create attendance records.', '2026-01-01T00:00:00Z'),
('perm_attendance_manual_entry', 'attendance.manual_entry', 'attendance', 'manual_entry', 'Create manual attendance entries.', '2026-01-01T00:00:00Z'),
('perm_attendance_edit', 'attendance.edit', 'attendance', 'edit', 'Edit attendance records.', '2026-01-01T00:00:00Z'),
('perm_attendance_delete', 'attendance.delete', 'attendance', 'delete', 'Delete attendance records.', '2026-01-01T00:00:00Z'),
('perm_attendance_approve_correction', 'attendance.approve_correction', 'attendance', 'approve_correction', 'Approve attendance corrections.', '2026-01-01T00:00:00Z'),
('perm_attendance_reject_correction', 'attendance.reject_correction', 'attendance', 'reject_correction', 'Reject attendance corrections.', '2026-01-01T00:00:00Z'),
('perm_attendance_resolve_conflicts', 'attendance.resolve_conflicts', 'attendance', 'resolve_conflicts', 'Resolve attendance conflicts.', '2026-01-01T00:00:00Z'),
('perm_attendance_export', 'attendance.export', 'attendance', 'export', 'Export attendance records.', '2026-01-01T00:00:00Z'),
('perm_attendance_manage_settings', 'attendance.manage_settings', 'attendance', 'manage_settings', 'Manage attendance settings.', '2026-01-01T00:00:00Z'),
('perm_attendance_view_conflicts', 'attendance.view_conflicts', 'attendance', 'view_conflicts', 'View attendance conflicts.', '2026-01-01T00:00:00Z'),
('perm_attendance_reports_view', 'attendance.reports.view', 'attendance', 'reports_view', 'View attendance reports.', '2026-01-01T00:00:00Z'),
('perm_attendance_reports_export_preview', 'attendance.reports.export_preview', 'attendance', 'reports_export_preview', 'Preview attendance report export data.', '2026-01-01T00:00:00Z'),
('perm_attendance_exceptions_view', 'attendance.exceptions.view', 'attendance', 'exceptions_view', 'View attendance exception reports.', '2026-01-01T00:00:00Z'),
('perm_attendance_device_punches_view', 'attendance.device_punches.view', 'attendance', 'device_punches_view', 'View attendance device punch reports.', '2026-01-01T00:00:00Z'),
('perm_attendance_lock', 'attendance.lock', 'attendance', 'lock', 'Lock attendance records.', '2026-01-01T00:00:00Z'),
('perm_attendance_unlock', 'attendance.unlock', 'attendance', 'unlock', 'Unlock attendance records.', '2026-01-01T00:00:00Z'),
('perm_kiosk_view', 'kiosk.view', 'kiosk', 'view', 'View kiosk attendance screen.', '2026-01-01T00:00:00Z'),
('perm_kiosk_clock_in', 'kiosk.clock_in', 'kiosk', 'clock_in', 'Clock in from kiosk.', '2026-01-01T00:00:00Z'),
('perm_kiosk_clock_out', 'kiosk.clock_out', 'kiosk', 'clock_out', 'Clock out from kiosk.', '2026-01-01T00:00:00Z'),
('perm_kiosk_sync', 'kiosk.sync', 'kiosk', 'sync', 'Sync kiosk attendance data.', '2026-01-01T00:00:00Z'),
('perm_kiosk_manage_device', 'kiosk.manage_device', 'kiosk', 'manage_device', 'Manage kiosk devices.', '2026-01-01T00:00:00Z'),
('perm_biometric_view', 'biometric.view', 'biometric', 'view', 'View biometric devices and logs.', '2026-01-01T00:00:00Z'),
('perm_biometric_manage_devices', 'biometric.manage_devices', 'biometric', 'manage_devices', 'Manage biometric devices.', '2026-01-01T00:00:00Z'),
('perm_biometric_enable_disable_device', 'biometric.enable_disable_device', 'biometric', 'enable_disable_device', 'Enable or disable biometric devices.', '2026-01-01T00:00:00Z'),
('perm_biometric_map_employee', 'biometric.map_employee', 'biometric', 'map_employee', 'Map employees to biometric users.', '2026-01-01T00:00:00Z'),
('perm_biometric_view_logs', 'biometric.view_logs', 'biometric', 'view_logs', 'View biometric attendance logs.', '2026-01-01T00:00:00Z'),
('perm_biometric_resolve_unmatched', 'biometric.resolve_unmatched', 'biometric', 'resolve_unmatched', 'Resolve unmatched biometric records.', '2026-01-01T00:00:00Z'),
('perm_biometric_resolve_punches', 'biometric.resolve_punches', 'biometric', 'resolve_punches', 'Resolve, link, or reject staged biometric punches.', '2026-01-01T00:00:00Z'),
('perm_biometric_sync', 'biometric.sync', 'biometric', 'sync', 'Sync biometric attendance logs.', '2026-01-01T00:00:00Z'),
('perm_leave_view', 'leave.view', 'leave', 'view', 'View leave records.', '2026-01-01T00:00:00Z'),
('perm_leave_create', 'leave.create', 'leave', 'create', 'Create leave requests.', '2026-01-01T00:00:00Z'),
('perm_leave_edit', 'leave.edit', 'leave', 'edit', 'Edit leave requests.', '2026-01-01T00:00:00Z'),
('perm_leave_approve', 'leave.approve', 'leave', 'approve', 'Approve leave requests.', '2026-01-01T00:00:00Z'),
('perm_leave_reject', 'leave.reject', 'leave', 'reject', 'Reject leave requests.', '2026-01-01T00:00:00Z'),
('perm_leave_cancel', 'leave.cancel', 'leave', 'cancel', 'Cancel leave requests.', '2026-01-01T00:00:00Z'),
('perm_leave_requests_submit', 'leave.requests.submit', 'leave', 'requests_submit', 'Submit leave requests for approval.', '2026-01-01T00:00:00Z'),
('perm_leave_requests_create_for_employee', 'leave.requests.create_for_employee', 'leave', 'requests_create_for_employee', 'Create leave requests on behalf of employees.', '2026-01-01T00:00:00Z'),
('perm_leave_requests_cancel', 'leave.requests.cancel', 'leave', 'requests_cancel', 'Cancel leave requests with audit history.', '2026-01-01T00:00:00Z'),
('perm_leave_requests_withdraw', 'leave.requests.withdraw', 'leave', 'requests_withdraw', 'Withdraw submitted leave requests.', '2026-01-01T00:00:00Z'),
('perm_leave_requests_override', 'leave.requests.override', 'leave', 'requests_override', 'Override leave request workflow rules with reason.', '2026-01-01T00:00:00Z'),
('perm_leave_approvals_view', 'leave.approvals.view', 'leave', 'approvals_view', 'View leave approval inbox, history, and detail.', '2026-01-01T00:00:00Z'),
('perm_leave_approvals_approve', 'leave.approvals.approve', 'leave', 'approvals_approve', 'Approve leave approval steps.', '2026-01-01T00:00:00Z'),
('perm_leave_approvals_reject', 'leave.approvals.reject', 'leave', 'approvals_reject', 'Reject leave approval steps.', '2026-01-01T00:00:00Z'),
('perm_leave_approvals_delegate', 'leave.approvals.delegate', 'leave', 'approvals_delegate', 'Delegate leave approval steps.', '2026-01-01T00:00:00Z'),
('perm_leave_approvals_escalate', 'leave.approvals.escalate', 'leave', 'approvals_escalate', 'Escalate leave approval steps.', '2026-01-01T00:00:00Z'),
('perm_leave_approvals_override', 'leave.approvals.override', 'leave', 'approvals_override', 'Override leave approvals with reason.', '2026-01-01T00:00:00Z'),
('perm_leave_approvals_settings_manage', 'leave.approvals.settings.manage', 'leave', 'approvals_settings_manage', 'Manage leave approval workflow settings.', '2026-01-01T00:00:00Z'),
('perm_leave_timeline_view', 'leave.timeline.view', 'leave', 'timeline_view', 'View leave request approval and balance timeline.', '2026-01-01T00:00:00Z'),
('perm_leave_manage_balances', 'leave.manage_balances', 'leave', 'manage_balances', 'Manage leave balances.', '2026-01-01T00:00:00Z'),
('perm_leave_balances_view', 'leave.balances.view', 'leave', 'balances_view', 'View leave balances.', '2026-01-01T00:00:00Z'),
('perm_leave_balances_manage', 'leave.balances.manage', 'leave', 'balances_manage', 'Manage leave balances.', '2026-01-01T00:00:00Z'),
('perm_leave_balances_adjust', 'leave.balances.adjust', 'leave', 'balances_adjust', 'Adjust leave balances.', '2026-01-01T00:00:00Z'),
('perm_leave_accrual_preview', 'leave.accrual.preview', 'leave', 'accrual_preview', 'Preview leave accrual.', '2026-01-01T00:00:00Z'),
('perm_leave_accrual_apply', 'leave.accrual.apply', 'leave', 'accrual_apply', 'Apply leave accrual.', '2026-01-01T00:00:00Z'),
('perm_leave_transactions_view', 'leave.transactions.view', 'leave', 'transactions_view', 'View leave balance transactions.', '2026-01-01T00:00:00Z'),
('perm_leave_policies_manage', 'leave.policies.manage', 'leave', 'policies_manage', 'Manage leave balance policies.', '2026-01-01T00:00:00Z'),
('perm_leave_export', 'leave.export', 'leave', 'export', 'Export leave records.', '2026-01-01T00:00:00Z'),
('perm_leave_settings_view', 'leave_settings.view', 'leave_settings', 'view', 'View leave settings.', '2026-01-01T00:00:00Z'),
('perm_leave_settings_manage', 'leave_settings.manage', 'leave_settings', 'manage', 'Manage leave settings.', '2026-01-01T00:00:00Z'),
('perm_leave_types_enable_disable', 'leave_types.enable_disable', 'leave_types', 'enable_disable', 'Enable or disable leave types.', '2026-01-01T00:00:00Z'),
('perm_leave_types_enable_disable_statutory', 'leave_types.enable_disable_statutory', 'leave_types', 'enable_disable_statutory', 'Enable or disable statutory leave types.', '2026-01-01T00:00:00Z'),
('perm_leave_policy_limits_edit', 'leave_policy_limits.edit', 'leave_policy_limits', 'edit', 'Edit leave policy limits.', '2026-01-01T00:00:00Z'),
('perm_leave_policy_override_manage', 'leave_policy_override.manage', 'leave_policy_override', 'manage', 'Manage leave policy overrides.', '2026-01-01T00:00:00Z'),
('perm_long_leave_view', 'long_leave.view', 'long_leave', 'view', 'View long leave records.', '2026-01-01T00:00:00Z'),
('perm_long_leave_create', 'long_leave.create', 'long_leave', 'create', 'Create long leave records.', '2026-01-01T00:00:00Z'),
('perm_long_leave_edit', 'long_leave.edit', 'long_leave', 'edit', 'Edit long leave records.', '2026-01-01T00:00:00Z'),
('perm_long_leave_submit', 'long_leave.submit', 'long_leave', 'submit', 'Submit long leave records for approval.', '2026-01-01T00:00:00Z'),
('perm_long_leave_approve', 'long_leave.approve', 'long_leave', 'approve', 'Approve long leave requests.', '2026-01-01T00:00:00Z'),
('perm_long_leave_reject', 'long_leave.reject', 'long_leave', 'reject', 'Reject long leave requests.', '2026-01-01T00:00:00Z'),
('perm_long_leave_cancel', 'long_leave.cancel', 'long_leave', 'cancel', 'Cancel long leave records.', '2026-01-01T00:00:00Z'),
('perm_long_leave_extend', 'long_leave.extend', 'long_leave', 'extend', 'Extend long leave records.', '2026-01-01T00:00:00Z'),
('perm_long_leave_return', 'long_leave.return', 'long_leave', 'return', 'Mark long leave employees returned.', '2026-01-01T00:00:00Z'),
('perm_long_leave_approve_salary_impact', 'long_leave.approve_salary_impact', 'long_leave', 'approve_salary_impact', 'Approve long leave salary impact.', '2026-01-01T00:00:00Z'),
('perm_long_leave_confirm_salary_impact', 'long_leave.confirm_salary_impact', 'long_leave', 'confirm_salary_impact', 'Confirm long leave salary impact.', '2026-01-01T00:00:00Z'),
('perm_long_leave_payroll_preview', 'long_leave.payroll_preview', 'long_leave', 'payroll_preview', 'Preview long leave payroll impact.', '2026-01-01T00:00:00Z'),
('perm_long_leave_payroll_apply', 'long_leave.payroll_apply', 'long_leave', 'payroll_apply', 'Apply reviewed long leave payroll impact.', '2026-01-01T00:00:00Z'),
('perm_long_leave_override', 'long_leave.override', 'long_leave', 'override', 'Override long leave rules with approval.', '2026-01-01T00:00:00Z'),
('perm_long_leave_return_confirm', 'long_leave.return_confirm', 'long_leave', 'return_confirm', 'Confirm employee return from long leave.', '2026-01-01T00:00:00Z'),
('perm_long_leave_settings_manage', 'long_leave.settings.manage', 'long_leave', 'settings_manage', 'Manage long leave settings.', '2026-01-01T00:00:00Z'),
('perm_long_leave_timeline_view', 'long_leave.timeline.view', 'long_leave', 'timeline_view', 'View long leave timelines.', '2026-01-01T00:00:00Z'),
('perm_payroll_view', 'payroll.view', 'payroll', 'view', 'View payroll runs.', '2026-01-01T00:00:00Z'),
('perm_payroll_calculate', 'payroll.calculate', 'payroll', 'calculate', 'Calculate payroll.', '2026-01-01T00:00:00Z'),
('perm_payroll_recalculate', 'payroll.recalculate', 'payroll', 'recalculate', 'Recalculate payroll.', '2026-01-01T00:00:00Z'),
('perm_payroll_review', 'payroll.review', 'payroll', 'review', 'Review payroll before approval.', '2026-01-01T00:00:00Z'),
('perm_payroll_approve', 'payroll.approve', 'payroll', 'approve', 'Approve payroll.', '2026-01-01T00:00:00Z'),
('perm_payroll_reject', 'payroll.reject', 'payroll', 'reject', 'Reject payroll.', '2026-01-01T00:00:00Z'),
('perm_payroll_finalize', 'payroll.finalize', 'payroll', 'finalize', 'Finalize payroll and apply approved repayments.', '2026-01-01T00:00:00Z'),
('perm_payroll_lock', 'payroll.lock', 'payroll', 'lock', 'Lock payroll.', '2026-01-01T00:00:00Z'),
('perm_payroll_request_reopen', 'payroll.request_reopen', 'payroll', 'request_reopen', 'Request payroll reopen.', '2026-01-01T00:00:00Z'),
('perm_payroll_approve_reopen', 'payroll.approve_reopen', 'payroll', 'approve_reopen', 'Approve payroll reopen.', '2026-01-01T00:00:00Z'),
('perm_payroll_reopen', 'payroll.reopen', 'payroll', 'reopen', 'Reopen payroll.', '2026-01-01T00:00:00Z'),
('perm_payroll_export', 'payroll.export', 'payroll', 'export', 'Export payroll data.', '2026-01-01T00:00:00Z'),
('perm_payroll_view_exceptions', 'payroll.view_exceptions', 'payroll', 'view_exceptions', 'View payroll exceptions.', '2026-01-01T00:00:00Z'),
('perm_payroll_resolve_exceptions', 'payroll.resolve_exceptions', 'payroll', 'resolve_exceptions', 'Resolve payroll exceptions.', '2026-01-01T00:00:00Z'),
('perm_payroll_manual_adjustment', 'payroll.manual_adjustment', 'payroll', 'manual_adjustment', 'Create payroll manual adjustments.', '2026-01-01T00:00:00Z'),
('perm_payroll_settings_view', 'payroll_settings.view', 'payroll_settings', 'view', 'View payroll settings.', '2026-01-01T00:00:00Z'),
('perm_payroll_settings_manage', 'payroll_settings.manage', 'payroll_settings', 'manage', 'Manage payroll settings.', '2026-01-01T00:00:00Z'),
('perm_salary_view', 'salary.view', 'salary', 'view', 'View salary records.', '2026-01-01T00:00:00Z'),
('perm_salary_create', 'salary.create', 'salary', 'create', 'Create salary records.', '2026-01-01T00:00:00Z'),
('perm_salary_edit', 'salary.edit', 'salary', 'edit', 'Edit salary records.', '2026-01-01T00:00:00Z'),
('perm_salary_increment_request', 'salary.increment_request', 'salary', 'increment_request', 'Request salary increment.', '2026-01-01T00:00:00Z'),
('perm_salary_increment_approve', 'salary.increment_approve', 'salary', 'increment_approve', 'Approve salary increment.', '2026-01-01T00:00:00Z'),
('perm_salary_history', 'salary.history', 'salary', 'history', 'View salary history.', '2026-01-01T00:00:00Z'),
('perm_salary_export', 'salary.export', 'salary', 'export', 'Export salary records.', '2026-01-01T00:00:00Z'),
('perm_payslips_view', 'payslips.view', 'payslips', 'view', 'View payslips.', '2026-01-01T00:00:00Z'),
('perm_payslips_generate', 'payslips.generate', 'payslips', 'generate', 'Generate payslips.', '2026-01-01T00:00:00Z'),
('perm_payslips_download', 'payslips.download', 'payslips', 'download', 'Download payslips.', '2026-01-01T00:00:00Z'),
('perm_payslips_print', 'payslips.print', 'payslips', 'print', 'Print payslips.', '2026-01-01T00:00:00Z'),
('perm_payslips_export', 'payslips.export', 'payslips', 'export', 'Export payslip records.', '2026-01-01T00:00:00Z'),
('perm_advances_view', 'advances.view', 'advances', 'view', 'View advance payments.', '2026-01-01T00:00:00Z'),
('perm_advances_create', 'advances.create', 'advances', 'create', 'Create advance payments.', '2026-01-01T00:00:00Z'),
('perm_advances_edit', 'advances.edit', 'advances', 'edit', 'Edit advance payments.', '2026-01-01T00:00:00Z'),
('perm_advances_approve', 'advances.approve', 'advances', 'approve', 'Approve advance payments.', '2026-01-01T00:00:00Z'),
('perm_advances_reject', 'advances.reject', 'advances', 'reject', 'Reject advance payments.', '2026-01-01T00:00:00Z'),
('perm_advances_export', 'advances.export', 'advances', 'export', 'Export advance payment records.', '2026-01-01T00:00:00Z'),
('perm_salary_loans_view', 'salary_loans.view', 'salary_loans', 'view', 'View salary loans.', '2026-01-01T00:00:00Z'),
('perm_salary_loans_create', 'salary_loans.create', 'salary_loans', 'create', 'Create salary loans.', '2026-01-01T00:00:00Z'),
('perm_salary_loans_edit', 'salary_loans.edit', 'salary_loans', 'edit', 'Edit salary loans.', '2026-01-01T00:00:00Z'),
('perm_salary_loans_approve', 'salary_loans.approve', 'salary_loans', 'approve', 'Approve salary loans.', '2026-01-01T00:00:00Z'),
('perm_salary_loans_pause', 'salary_loans.pause', 'salary_loans', 'pause', 'Pause salary loans.', '2026-01-01T00:00:00Z'),
('perm_salary_loans_settle', 'salary_loans.settle', 'salary_loans', 'settle', 'Settle salary loans.', '2026-01-01T00:00:00Z'),
('perm_salary_loans_export', 'salary_loans.export', 'salary_loans', 'export', 'Export salary loan records.', '2026-01-01T00:00:00Z'),
('perm_holidays_view', 'holidays.view', 'holidays', 'view', 'View holidays.', '2026-01-01T00:00:00Z'),
('perm_holidays_create', 'holidays.create', 'holidays', 'create', 'Create holidays.', '2026-01-01T00:00:00Z'),
('perm_holidays_edit', 'holidays.edit', 'holidays', 'edit', 'Edit holidays.', '2026-01-01T00:00:00Z'),
('perm_holidays_delete', 'holidays.delete', 'holidays', 'delete', 'Delete holidays.', '2026-01-01T00:00:00Z'),
('perm_holidays_enable_disable', 'holidays.enable_disable', 'holidays', 'enable_disable', 'Enable or disable holidays.', '2026-01-01T00:00:00Z'),
('perm_holidays_manage_public', 'holidays.manage_public', 'holidays', 'manage_public', 'Manage public holidays.', '2026-01-01T00:00:00Z'),
('perm_holidays_manage_company', 'holidays.manage_company', 'holidays', 'manage_company', 'Manage company holidays.', '2026-01-01T00:00:00Z'),
('perm_holidays_manage_other', 'holidays.manage_other', 'holidays', 'manage_other', 'Manage other holidays.', '2026-01-01T00:00:00Z'),
('perm_holidays_manage_outlet_specific', 'holidays.manage_outlet_specific', 'holidays', 'manage_outlet_specific', 'Manage outlet-specific holidays.', '2026-01-01T00:00:00Z'),
('perm_holidays_payroll_rules_manage', 'holidays.payroll_rules.manage', 'holidays', 'payroll_rules_manage', 'Manage holiday payroll rules.', '2026-01-01T00:00:00Z'),
('perm_holidays_leave_rules_manage', 'holidays.leave_rules.manage', 'holidays', 'leave_rules_manage', 'Manage holiday leave rules.', '2026-01-01T00:00:00Z'),
('perm_holidays_attendance_rules_manage', 'holidays.attendance_rules.manage', 'holidays', 'attendance_rules_manage', 'Manage holiday attendance rules.', '2026-01-01T00:00:00Z'),
('perm_holidays_roster_rules_manage', 'holidays.roster_rules.manage', 'holidays', 'roster_rules_manage', 'Manage holiday roster rules.', '2026-01-01T00:00:00Z'),
('perm_holidays_archive', 'holidays.archive', 'holidays', 'archive', 'Archive holiday records with audit history.', '2026-01-01T00:00:00Z'),
('perm_holidays_restore', 'holidays.restore', 'holidays', 'restore', 'Restore archived holiday records.', '2026-01-01T00:00:00Z'),
('perm_holidays_import', 'holidays.import', 'holidays', 'import', 'Bulk import or upsert holiday records.', '2026-01-01T00:00:00Z'),
('perm_holidays_settings_manage', 'holidays.settings.manage', 'holidays', 'settings_manage', 'Manage holiday calendar settings.', '2026-01-01T00:00:00Z'),
('perm_holidays_calendar_view', 'holidays.calendar.view', 'holidays', 'calendar_view', 'View expanded holiday calendar events.', '2026-01-01T00:00:00Z'),
('perm_holidays_override', 'holidays.override', 'holidays', 'override', 'Override holiday warnings with reason.', '2026-01-01T00:00:00Z'),
('perm_holidays_audit_view', 'holidays.audit.view', 'holidays', 'audit_view', 'View holiday audit history.', '2026-01-01T00:00:00Z'),
('perm_roster_view', 'roster.view', 'roster', 'view', 'View roster.', '2026-01-01T00:00:00Z'),
('perm_roster_create', 'roster.create', 'roster', 'create', 'Create roster shifts.', '2026-01-01T00:00:00Z'),
('perm_roster_edit', 'roster.edit', 'roster', 'edit', 'Edit roster shifts.', '2026-01-01T00:00:00Z'),
('perm_roster_delete', 'roster.delete', 'roster', 'delete', 'Delete roster shifts.', '2026-01-01T00:00:00Z'),
('perm_roster_publish', 'roster.publish', 'roster', 'publish', 'Publish roster.', '2026-01-01T00:00:00Z'),
('perm_roster_unpublish', 'roster.unpublish', 'roster', 'unpublish', 'Unpublish roster.', '2026-01-01T00:00:00Z'),
('perm_roster_copy_week', 'roster.copy_week', 'roster', 'copy_week', 'Copy weekly roster.', '2026-01-01T00:00:00Z'),
('perm_roster_view_conflicts', 'roster.view_conflicts', 'roster', 'view_conflicts', 'View roster conflicts.', '2026-01-01T00:00:00Z'),
('perm_roster_resolve_conflicts', 'roster.resolve_conflicts', 'roster', 'resolve_conflicts', 'Resolve roster conflicts.', '2026-01-01T00:00:00Z'),
('perm_roster_export', 'roster.export', 'roster', 'export', 'Export roster.', '2026-01-01T00:00:00Z'),
('perm_roster_settings_manage', 'roster_settings.manage', 'roster_settings', 'manage', 'Manage roster settings.', '2026-01-01T00:00:00Z'),
('perm_assets_view', 'assets.view', 'assets', 'view', 'View assets.', '2026-01-01T00:00:00Z'),
('perm_assets_create', 'assets.create', 'assets', 'create', 'Create assets.', '2026-01-01T00:00:00Z'),
('perm_assets_edit', 'assets.edit', 'assets', 'edit', 'Edit assets.', '2026-01-01T00:00:00Z'),
('perm_assets_delete', 'assets.delete', 'assets', 'delete', 'Delete assets.', '2026-01-01T00:00:00Z'),
('perm_assets_assign', 'assets.assign', 'assets', 'assign', 'Assign assets.', '2026-01-01T00:00:00Z'),
('perm_assets_return', 'assets.return', 'assets', 'return', 'Return assets.', '2026-01-01T00:00:00Z'),
('perm_assets_mark_lost', 'assets.mark_lost', 'assets', 'mark_lost', 'Mark assets as lost.', '2026-01-01T00:00:00Z'),
('perm_assets_mark_damaged', 'assets.mark_damaged', 'assets', 'mark_damaged', 'Mark assets as damaged.', '2026-01-01T00:00:00Z'),
('perm_assets_request_deduction', 'assets.request_deduction', 'assets', 'request_deduction', 'Request asset deduction.', '2026-01-01T00:00:00Z'),
('perm_assets_approve_deduction', 'assets.approve_deduction', 'assets', 'approve_deduction', 'Approve asset deduction.', '2026-01-01T00:00:00Z'),
('perm_assets_export', 'assets.export', 'assets', 'export', 'Export asset records.', '2026-01-01T00:00:00Z'),
('perm_uniforms_view', 'uniforms.view', 'uniforms', 'view', 'View uniform issues.', '2026-01-01T00:00:00Z'),
('perm_uniforms_issue', 'uniforms.issue', 'uniforms', 'issue', 'Issue uniforms.', '2026-01-01T00:00:00Z'),
('perm_uniforms_return', 'uniforms.return', 'uniforms', 'return', 'Return uniforms.', '2026-01-01T00:00:00Z'),
('perm_uniforms_pending_return', 'uniforms.pending_return', 'uniforms', 'pending_return', 'View pending uniform returns.', '2026-01-01T00:00:00Z'),
('perm_uniforms_export', 'uniforms.export', 'uniforms', 'export', 'Export uniform records.', '2026-01-01T00:00:00Z'),
('perm_assets_settings_manage', 'assets_settings.manage', 'assets_settings', 'manage', 'Manage asset and uniform settings.', '2026-01-01T00:00:00Z'),
('perm_documents_view', 'documents.view', 'documents', 'view', 'View documents.', '2026-01-01T00:00:00Z'),
('perm_documents_view_sensitive', 'documents.view_sensitive', 'documents', 'view_sensitive', 'View sensitive documents.', '2026-01-01T00:00:00Z'),
('perm_documents_upload', 'documents.upload', 'documents', 'upload', 'Upload documents.', '2026-01-01T00:00:00Z'),
('perm_documents_download', 'documents.download', 'documents', 'download', 'Download documents.', '2026-01-01T00:00:00Z'),
('perm_documents_edit', 'documents.edit', 'documents', 'edit', 'Edit documents.', '2026-01-01T00:00:00Z'),
('perm_documents_delete', 'documents.delete', 'documents', 'delete', 'Delete documents.', '2026-01-01T00:00:00Z'),
('perm_documents_view_expiring', 'documents.view_expiring', 'documents', 'view_expiring', 'View expiring documents.', '2026-01-01T00:00:00Z'),
('perm_documents_view_missing', 'documents.view_missing', 'documents', 'view_missing', 'View missing documents.', '2026-01-01T00:00:00Z'),
('perm_documents_export', 'documents.export', 'documents', 'export', 'Export document reports.', '2026-01-01T00:00:00Z'),
('perm_documents_settings_manage', 'documents_settings.manage', 'documents_settings', 'manage', 'Manage document settings.', '2026-01-01T00:00:00Z'),
('perm_approvals_view', 'approvals.view', 'approvals', 'view', 'View approval requests.', '2026-01-01T00:00:00Z'),
('perm_approvals_approve', 'approvals.approve', 'approvals', 'approve', 'Approve requests.', '2026-01-01T00:00:00Z'),
('perm_approvals_reject', 'approvals.reject', 'approvals', 'reject', 'Reject requests.', '2026-01-01T00:00:00Z'),
('perm_approvals_return', 'approvals.return', 'approvals', 'return', 'Return requests for changes.', '2026-01-01T00:00:00Z'),
('perm_approvals_override', 'approvals.override', 'approvals', 'override', 'Override approvals when permitted.', '2026-01-01T00:00:00Z'),
('perm_approvals_view_history', 'approvals.view_history', 'approvals', 'view_history', 'View approval history.', '2026-01-01T00:00:00Z'),
('perm_approval_workflows_view', 'approval_workflows.view', 'approval_workflows', 'view', 'View approval workflows.', '2026-01-01T00:00:00Z'),
('perm_approval_workflows_manage', 'approval_workflows.manage', 'approval_workflows', 'manage', 'Manage approval workflows.', '2026-01-01T00:00:00Z'),
('perm_approval_thresholds_view', 'approval_thresholds.view', 'approval_thresholds', 'view', 'View approval thresholds.', '2026-01-01T00:00:00Z'),
('perm_approval_thresholds_edit', 'approval_thresholds.edit', 'approval_thresholds', 'edit', 'Edit approval thresholds.', '2026-01-01T00:00:00Z'),
('perm_approval_thresholds_approve_changes', 'approval_thresholds.approve_changes', 'approval_thresholds', 'approve_changes', 'Approve approval threshold changes.', '2026-01-01T00:00:00Z'),
('perm_approval_thresholds_reset_defaults', 'approval_thresholds.reset_defaults', 'approval_thresholds', 'reset_defaults', 'Reset approval thresholds to defaults.', '2026-01-01T00:00:00Z'),
('perm_users_view', 'users.view', 'users', 'view', 'View users.', '2026-01-01T00:00:00Z'),
('perm_users_create', 'users.create', 'users', 'create', 'Create users.', '2026-01-01T00:00:00Z'),
('perm_users_edit', 'users.edit', 'users', 'edit', 'Edit users.', '2026-01-01T00:00:00Z'),
('perm_users_disable', 'users.disable', 'users', 'disable', 'Disable users.', '2026-01-01T00:00:00Z'),
('perm_users_enable', 'users.enable', 'users', 'enable', 'Enable users.', '2026-01-01T00:00:00Z'),
('perm_users_reset_password', 'users.reset_password', 'users', 'reset_password', 'Reset user passwords.', '2026-01-01T00:00:00Z'),
('perm_users_revoke_sessions', 'users.revoke_sessions', 'users', 'revoke_sessions', 'Revoke user sessions.', '2026-01-01T00:00:00Z'),
('perm_users_sessions_view', 'users.sessions.view', 'users', 'sessions_view', 'View user active sessions.', '2026-01-01T00:00:00Z'),
('perm_users_sessions_revoke', 'users.sessions.revoke', 'users', 'sessions_revoke', 'Revoke a specific user session.', '2026-01-01T00:00:00Z'),
('perm_users_sessions_revoke_all', 'users.sessions.revoke_all', 'users', 'sessions_revoke_all', 'Revoke all active sessions for a user.', '2026-01-01T00:00:00Z'),
('perm_roles_view', 'roles.view', 'roles', 'view', 'View roles.', '2026-01-01T00:00:00Z'),
('perm_roles_create', 'roles.create', 'roles', 'create', 'Create roles.', '2026-01-01T00:00:00Z'),
('perm_roles_edit', 'roles.edit', 'roles', 'edit', 'Edit roles.', '2026-01-01T00:00:00Z'),
('perm_roles_delete', 'roles.delete', 'roles', 'delete', 'Delete roles.', '2026-01-01T00:00:00Z'),
('perm_permissions_view', 'permissions.view', 'permissions', 'view', 'View permissions.', '2026-01-01T00:00:00Z'),
('perm_permissions_manage', 'permissions.manage', 'permissions', 'manage', 'Manage permissions.', '2026-01-01T00:00:00Z'),
('perm_security_2fa_view', 'security.2fa.view', 'security', '2fa_view', 'View two-factor authentication settings.', '2026-01-01T00:00:00Z'),
('perm_security_2fa_manage_own', 'security.2fa.manage_own', 'security', '2fa_manage_own', 'Manage own two-factor authentication.', '2026-01-01T00:00:00Z'),
('perm_security_2fa_disable_user_2fa', 'security.2fa.disable_user_2fa', 'security', '2fa_disable_user_2fa', 'Disable user two-factor authentication.', '2026-01-01T00:00:00Z'),
('perm_security_2fa_require_for_roles', 'security.2fa.require_for_roles', 'security', '2fa_require_for_roles', 'Require two-factor authentication for roles.', '2026-01-01T00:00:00Z'),
('perm_security_settings_view', 'security_settings.view', 'security_settings', 'view', 'View security settings.', '2026-01-01T00:00:00Z'),
('perm_security_settings_manage', 'security_settings.manage', 'security_settings', 'manage', 'Manage security settings.', '2026-01-01T00:00:00Z'),
('perm_settings_view', 'settings.view', 'settings', 'view', 'View settings.', '2026-01-01T00:00:00Z'),
('perm_settings_manage', 'settings.manage', 'settings', 'manage', 'Manage settings.', '2026-01-01T00:00:00Z'),
('perm_feature_settings_view', 'feature_settings.view', 'feature_settings', 'view', 'View feature settings.', '2026-01-01T00:00:00Z'),
('perm_feature_settings_manage', 'feature_settings.manage', 'feature_settings', 'manage', 'Manage feature settings.', '2026-01-01T00:00:00Z'),
('perm_attendance_settings_view', 'attendance_settings.view', 'attendance_settings', 'view', 'View attendance settings.', '2026-01-01T00:00:00Z'),
('perm_attendance_settings_manage', 'attendance_settings.manage', 'attendance_settings', 'manage', 'Manage attendance settings.', '2026-01-01T00:00:00Z'),
('perm_holiday_settings_view', 'holiday_settings.view', 'holiday_settings', 'view', 'View holiday settings.', '2026-01-01T00:00:00Z'),
('perm_holiday_settings_manage', 'holiday_settings.manage', 'holiday_settings', 'manage', 'Manage holiday settings.', '2026-01-01T00:00:00Z'),
('perm_sync_settings_view', 'sync_settings.view', 'sync_settings', 'view', 'View sync settings.', '2026-01-01T00:00:00Z'),
('perm_sync_settings_manage', 'sync_settings.manage', 'sync_settings', 'manage', 'Manage sync settings.', '2026-01-01T00:00:00Z'),
('perm_realtime_settings_view', 'realtime_settings.view', 'realtime_settings', 'view', 'View realtime settings.', '2026-01-01T00:00:00Z'),
('perm_realtime_settings_manage', 'realtime_settings.manage', 'realtime_settings', 'manage', 'Manage realtime settings.', '2026-01-01T00:00:00Z'),
('perm_backup_settings_view', 'backup_settings.view', 'backup_settings', 'view', 'View backup settings.', '2026-01-01T00:00:00Z'),
('perm_backup_settings_manage', 'backup_settings.manage', 'backup_settings', 'manage', 'Manage backup settings.', '2026-01-01T00:00:00Z'),
('perm_audit_settings_view', 'audit_settings.view', 'audit_settings', 'view', 'View audit settings.', '2026-01-01T00:00:00Z'),
('perm_audit_settings_manage', 'audit_settings.manage', 'audit_settings', 'manage', 'Manage audit settings.', '2026-01-01T00:00:00Z'),
('perm_import_export_settings_view', 'import_export_settings.view', 'import_export_settings', 'view', 'View import and export settings.', '2026-01-01T00:00:00Z'),
('perm_import_export_settings_manage', 'import_export_settings.manage', 'import_export_settings', 'manage', 'Manage import and export settings.', '2026-01-01T00:00:00Z'),
('perm_sync_view', 'sync.view', 'sync', 'view', 'View sync activity.', '2026-01-01T00:00:00Z'),
('perm_sync_manage', 'sync.manage', 'sync', 'manage', 'Manage sync workflows.', '2026-01-01T00:00:00Z'),
('perm_sync_retry', 'sync.retry', 'sync', 'retry', 'Retry sync items.', '2026-01-01T00:00:00Z'),
('perm_sync_resolve_conflicts', 'sync.resolve_conflicts', 'sync', 'resolve_conflicts', 'Resolve sync conflicts.', '2026-01-01T00:00:00Z'),
('perm_sync_force_resync', 'sync.force_resync', 'sync', 'force_resync', 'Force device resync.', '2026-01-01T00:00:00Z'),
('perm_sync_register_device', 'sync.register_device', 'sync', 'register_device', 'Register sync devices.', '2026-01-01T00:00:00Z'),
('perm_sync_disable_device', 'sync.disable_device', 'sync', 'disable_device', 'Disable sync devices.', '2026-01-01T00:00:00Z'),
('perm_sync_view_device_health', 'sync.view_device_health', 'sync', 'view_device_health', 'View sync device health.', '2026-01-01T00:00:00Z'),
('perm_sync_manage_settings', 'sync.manage_settings', 'sync', 'manage_settings', 'Manage sync settings.', '2026-01-01T00:00:00Z'),
('perm_devices_view', 'devices.view', 'devices', 'view', 'View devices.', '2026-01-01T00:00:00Z'),
('perm_devices_register', 'devices.register', 'devices', 'register', 'Register devices.', '2026-01-01T00:00:00Z'),
('perm_devices_edit', 'devices.edit', 'devices', 'edit', 'Edit devices.', '2026-01-01T00:00:00Z'),
('perm_devices_enable', 'devices.enable', 'devices', 'enable', 'Enable devices.', '2026-01-01T00:00:00Z'),
('perm_devices_disable', 'devices.disable', 'devices', 'disable', 'Disable devices.', '2026-01-01T00:00:00Z'),
('perm_devices_revoke', 'devices.revoke', 'devices', 'revoke', 'Revoke device access.', '2026-01-01T00:00:00Z'),
('perm_devices_rotate_token', 'devices.rotate_token', 'devices', 'rotate_token', 'Rotate device token.', '2026-01-01T00:00:00Z'),
('perm_devices_view_health', 'devices.view_health', 'devices', 'view_health', 'View device health.', '2026-01-01T00:00:00Z'),
('perm_dashboard_view', 'dashboard.view', 'dashboard', 'view', 'View the HR dashboard.', '2026-01-01T00:00:00Z'),
('perm_dashboard_view_company', 'dashboard.view_company', 'dashboard', 'view_company', 'View company-wide dashboard widgets.', '2026-01-01T00:00:00Z'),
('perm_dashboard_view_outlet', 'dashboard.view_outlet', 'dashboard', 'view_outlet', 'View outlet-scoped dashboard widgets.', '2026-01-01T00:00:00Z'),
('perm_dashboard_attendance_view', 'dashboard.attendance.view', 'dashboard', 'attendance_view', 'View dashboard attendance widgets.', '2026-01-01T00:00:00Z'),
('perm_dashboard_leave_view', 'dashboard.leave.view', 'dashboard', 'leave_view', 'View dashboard leave and approval widgets.', '2026-01-01T00:00:00Z'),
('perm_dashboard_long_leave_view', 'dashboard.long_leave.view', 'dashboard', 'long_leave_view', 'View dashboard long leave widgets.', '2026-01-01T00:00:00Z'),
('perm_dashboard_expiry_alerts_view', 'dashboard.expiry_alerts.view', 'dashboard', 'expiry_alerts_view', 'View dashboard expiry alert widgets.', '2026-01-01T00:00:00Z'),
('perm_dashboard_device_health_view', 'dashboard.device_health.view', 'dashboard', 'device_health_view', 'View dashboard device health widgets.', '2026-01-01T00:00:00Z'),
('perm_dashboard_payroll_readiness_view', 'dashboard.payroll_readiness.view', 'dashboard', 'payroll_readiness_view', 'View dashboard payroll readiness widgets.', '2026-01-01T00:00:00Z'),
('perm_dashboard_admin_health_view', 'dashboard.admin_health.view', 'dashboard', 'admin_health_view', 'View admin-only dashboard health widgets.', '2026-01-01T00:00:00Z'),
('perm_reports_view', 'reports.view', 'reports', 'view', 'View reports.', '2026-01-01T00:00:00Z'),
('perm_reports_export', 'reports.export', 'reports', 'export', 'Export reports.', '2026-01-01T00:00:00Z'),
('perm_reports_saved_filters_manage', 'reports.saved_filters.manage', 'reports', 'saved_filters_manage', 'Manage saved report filters.', '2026-01-01T00:00:00Z'),
('perm_import_view', 'import.view', 'import', 'view', 'View import batches.', '2026-01-01T00:00:00Z'),
('perm_import_create', 'import.create', 'import', 'create', 'Create import batches.', '2026-01-01T00:00:00Z'),
('perm_import_confirm', 'import.confirm', 'import', 'confirm', 'Confirm imports.', '2026-01-01T00:00:00Z'),
('perm_import_rollback', 'import.rollback', 'import', 'rollback', 'Rollback imports.', '2026-01-01T00:00:00Z'),
('perm_import_download_template', 'import.download_template', 'import', 'download_template', 'Download import templates.', '2026-01-01T00:00:00Z'),
('perm_export_view', 'export.view', 'export', 'view', 'View export jobs.', '2026-01-01T00:00:00Z'),
('perm_export_create', 'export.create', 'export', 'create', 'Create export jobs.', '2026-01-01T00:00:00Z'),
('perm_export_download', 'export.download', 'export', 'download', 'Download export files.', '2026-01-01T00:00:00Z'),
('perm_export_sensitive', 'export.sensitive', 'export', 'sensitive', 'Export sensitive data.', '2026-01-01T00:00:00Z'),
('perm_export_full_company_data', 'export.full_company_data', 'export', 'full_company_data', 'Export full company data.', '2026-01-01T00:00:00Z'),
('perm_audit_logs_view', 'audit_logs.view', 'audit_logs', 'view', 'View audit logs.', '2026-01-01T00:00:00Z'),
('perm_audit_logs_export', 'audit_logs.export', 'audit_logs', 'export', 'Export audit logs.', '2026-01-01T00:00:00Z'),
('perm_audit_logs_view_sensitive', 'audit_logs.view_sensitive', 'audit_logs', 'view_sensitive', 'View sensitive audit log details.', '2026-01-01T00:00:00Z'),
('perm_backup_view', 'backup.view', 'backup', 'view', 'View backups.', '2026-01-01T00:00:00Z'),
('perm_backup_create', 'backup.create', 'backup', 'create', 'Create backups.', '2026-01-01T00:00:00Z'),
('perm_backup_download', 'backup.download', 'backup', 'download', 'Download backups.', '2026-01-01T00:00:00Z'),
('perm_backup_restore_request', 'backup.restore_request', 'backup', 'restore_request', 'Request restore from backup.', '2026-01-01T00:00:00Z'),
('perm_backup_restore_approve', 'backup.restore_approve', 'backup', 'restore_approve', 'Approve restore requests.', '2026-01-01T00:00:00Z'),
('perm_backup_manage_settings', 'backup.manage_settings', 'backup', 'manage_settings', 'Manage backup settings.', '2026-01-01T00:00:00Z'),
('perm_backup_view_history', 'backup.view_history', 'backup', 'view_history', 'View backup history.', '2026-01-01T00:00:00Z'),
('perm_backup_recovery_view', 'backup_recovery.view', 'backup_recovery', 'view', 'View backup and restore jobs.', '2026-01-01T00:00:00Z'),
('perm_backup_recovery_backup_create', 'backup_recovery.backup.create', 'backup_recovery', 'backup_create', 'Create backup jobs.', '2026-01-01T00:00:00Z'),
('perm_backup_recovery_backup_generate', 'backup_recovery.backup.generate', 'backup_recovery', 'backup_generate', 'Generate backup files.', '2026-01-01T00:00:00Z'),
('perm_backup_recovery_backup_download', 'backup_recovery.backup.download', 'backup_recovery', 'backup_download', 'Download backup files.', '2026-01-01T00:00:00Z'),
('perm_backup_recovery_backup_cancel', 'backup_recovery.backup.cancel', 'backup_recovery', 'backup_cancel', 'Cancel backup jobs.', '2026-01-01T00:00:00Z'),
('perm_backup_recovery_restore_create', 'backup_recovery.restore.create', 'backup_recovery', 'restore_create', 'Create restore jobs.', '2026-01-01T00:00:00Z'),
('perm_backup_recovery_restore_preview', 'backup_recovery.restore.preview', 'backup_recovery', 'restore_preview', 'Validate and preview restore jobs.', '2026-01-01T00:00:00Z'),
('perm_backup_recovery_restore_apply', 'backup_recovery.restore.apply', 'backup_recovery', 'restore_apply', 'Apply restore jobs with confirmation.', '2026-01-01T00:00:00Z'),
('perm_backup_recovery_restore_cancel', 'backup_recovery.restore.cancel', 'backup_recovery', 'restore_cancel', 'Cancel restore jobs.', '2026-01-01T00:00:00Z'),
('perm_backup_recovery_settings_manage', 'backup_recovery.settings.manage', 'backup_recovery', 'settings_manage', 'Manage backup and restore settings.', '2026-01-01T00:00:00Z'),
('perm_backup_recovery_audit_view', 'backup_recovery.audit.view', 'backup_recovery', 'audit_view', 'View backup and restore audit summaries.', '2026-01-01T00:00:00Z'),
('perm_system_health_view', 'system.health.view', 'system', 'health_view', 'View system health.', '2026-01-01T00:00:00Z'),
('perm_system_errors_view', 'system.errors.view', 'system', 'errors_view', 'View system errors.', '2026-01-01T00:00:00Z'),
('perm_system_cost_view', 'system.cost.view', 'system', 'cost_view', 'View system cost information.', '2026-01-01T00:00:00Z'),
('perm_notifications_view', 'notifications.view', 'notifications', 'view', 'View notifications.', '2026-01-01T00:00:00Z'),
('perm_notifications_manage', 'notifications.manage', 'notifications', 'manage', 'Manage notifications.', '2026-01-01T00:00:00Z'),
('perm_notifications_manage_own', 'notifications.manage_own', 'notifications', 'manage_own', 'Manage own in-app notifications.', '2026-01-01T00:00:00Z'),
('perm_notifications_mark_read', 'notifications.mark_read', 'notifications', 'mark_read', 'Mark own notifications read or unread.', '2026-01-01T00:00:00Z'),
('perm_notifications_archive', 'notifications.archive', 'notifications', 'archive', 'Archive or dismiss own notifications.', '2026-01-01T00:00:00Z'),
('perm_notifications_preferences_manage', 'notifications.preferences.manage', 'notifications', 'preferences_manage', 'Manage own in-app notification preferences.', '2026-01-01T00:00:00Z'),
('perm_notifications_admin_view', 'notifications.admin.view', 'notifications', 'admin_view', 'View notification delivery summaries.', '2026-01-01T00:00:00Z'),
('perm_notifications_admin_manage', 'notifications.admin.manage', 'notifications', 'admin_manage', 'Manage notification administration records.', '2026-01-01T00:00:00Z'),
('perm_notifications_audit_view', 'notifications.audit.view', 'notifications', 'audit_view', 'View notification audit and delivery history.', '2026-01-01T00:00:00Z'),
('perm_email_notifications_view_own', 'email_notifications.view_own', 'notifications', 'email_view_own', 'View own email notification delivery records.', '2026-01-01T00:00:00Z'),
('perm_email_notifications_preferences_manage', 'email_notifications.preferences.manage', 'notifications', 'email_preferences_manage', 'Manage own email notification preferences.', '2026-01-01T00:00:00Z'),
('perm_email_notifications_admin_view', 'email_notifications.admin.view', 'notifications', 'email_admin_view', 'View email notification delivery logs.', '2026-01-01T00:00:00Z'),
('perm_email_notifications_admin_manage', 'email_notifications.admin.manage', 'notifications', 'email_admin_manage', 'Manage email notification delivery administration.', '2026-01-01T00:00:00Z'),
('perm_email_notifications_retry', 'email_notifications.retry', 'notifications', 'email_retry', 'Retry failed email notification jobs.', '2026-01-01T00:00:00Z'),
('perm_email_notifications_process', 'email_notifications.process', 'notifications', 'email_process', 'Process pending email notification jobs.', '2026-01-01T00:00:00Z'),
('perm_email_notifications_templates_view', 'email_notifications.templates.view', 'notifications', 'email_templates_view', 'View email notification templates.', '2026-01-01T00:00:00Z'),
('perm_email_notifications_templates_manage', 'email_notifications.templates.manage', 'notifications', 'email_templates_manage', 'Manage email notification templates.', '2026-01-01T00:00:00Z'),
('perm_email_notifications_settings_manage', 'email_notifications.settings.manage', 'notifications', 'email_settings_manage', 'Manage email notification settings.', '2026-01-01T00:00:00Z'),
('perm_email_notifications_audit_view', 'email_notifications.audit.view', 'notifications', 'email_audit_view', 'View email notification audit history.', '2026-01-01T00:00:00Z'),
('perm_expiry_alerts_view', 'expiry_alerts.view', 'expiry_alerts', 'view', 'View expiry alerts for documents, contracts, employee identity dates, and long leave returns.', '2026-01-01T00:00:00Z'),
('perm_expiry_alerts_view_own', 'expiry_alerts.view_own', 'expiry_alerts', 'view_own', 'View own expiry alerts where self-service is enabled.', '2026-01-01T00:00:00Z'),
('perm_expiry_alerts_scan', 'expiry_alerts.scan', 'expiry_alerts', 'scan', 'Preview and run expiry alert scans.', '2026-01-01T00:00:00Z'),
('perm_expiry_alerts_manage', 'expiry_alerts.manage', 'expiry_alerts', 'manage', 'Manage expiry alert lifecycle actions.', '2026-01-01T00:00:00Z'),
('perm_expiry_alerts_acknowledge', 'expiry_alerts.acknowledge', 'expiry_alerts', 'acknowledge', 'Acknowledge expiry alerts.', '2026-01-01T00:00:00Z'),
('perm_expiry_alerts_resolve', 'expiry_alerts.resolve', 'expiry_alerts', 'resolve', 'Resolve expiry alerts with a reason.', '2026-01-01T00:00:00Z'),
('perm_expiry_alerts_dismiss', 'expiry_alerts.dismiss', 'expiry_alerts', 'dismiss', 'Dismiss expiry alerts with a reason.', '2026-01-01T00:00:00Z'),
('perm_expiry_alerts_snooze', 'expiry_alerts.snooze', 'expiry_alerts', 'snooze', 'Snooze expiry alerts until a later review date.', '2026-01-01T00:00:00Z'),
('perm_expiry_alerts_settings_manage', 'expiry_alerts.settings.manage', 'expiry_alerts', 'settings_manage', 'Manage expiry alert settings.', '2026-01-01T00:00:00Z'),
('perm_expiry_alerts_audit_view', 'expiry_alerts.audit.view', 'expiry_alerts', 'audit_view', 'View expiry alert audit history.', '2026-01-01T00:00:00Z');

INSERT OR IGNORE INTO permissions (id, permission_key, module, action, description, created_at) VALUES
('perm_hr_reports_view', 'hr_reports.view', 'hr_reports', 'view', 'View HR report pages and report data.', '2026-01-01T00:00:00Z'),
('perm_hr_reports_employee_view', 'hr_reports.employee.view', 'hr_reports', 'employee_view', 'View employee master, status, headcount, probation, and new joiner reports.', '2026-01-01T00:00:00Z'),
('perm_hr_reports_compliance_view', 'hr_reports.compliance.view', 'hr_reports', 'compliance_view', 'View HR compliance, contracts, and foreign employee compliance reports.', '2026-01-01T00:00:00Z'),
('perm_hr_reports_documents_view', 'hr_reports.documents.view', 'hr_reports', 'documents_view', 'View HR document compliance reports.', '2026-01-01T00:00:00Z'),
('perm_hr_reports_leave_view', 'hr_reports.leave.view', 'hr_reports', 'leave_view', 'View HR leave balance and leave request reports.', '2026-01-01T00:00:00Z'),
('perm_hr_reports_long_leave_view', 'hr_reports.long_leave.view', 'hr_reports', 'long_leave_view', 'View HR long leave reports.', '2026-01-01T00:00:00Z'),
('perm_hr_reports_assets_view', 'hr_reports.assets.view', 'hr_reports', 'assets_view', 'View HR asset and uniform assignment reports.', '2026-01-01T00:00:00Z'),
('perm_hr_reports_lifecycle_view', 'hr_reports.lifecycle.view', 'hr_reports', 'lifecycle_view', 'View HR employee lifecycle and safe history reports.', '2026-01-01T00:00:00Z'),
('perm_hr_reports_employee_360_view', 'hr_reports.employee_360.view', 'hr_reports', 'employee_360_view', 'View Employee 360 summary reports.', '2026-01-01T00:00:00Z'),
('perm_hr_reports_catalog_view', 'hr_reports.catalog.view', 'hr_reports', 'catalog_view', 'View the HR report catalog.', '2026-01-01T00:00:00Z');

INSERT OR IGNORE INTO permissions (id, permission_key, module, action, description, created_at) VALUES
('perm_payroll_reports_view', 'payroll_reports.view', 'payroll_reports', 'view', 'View payroll and finance report pages and report data.', '2026-01-01T00:00:00Z'),
('perm_payroll_reports_catalog_view', 'payroll_reports.catalog.view', 'payroll_reports', 'catalog_view', 'View the payroll report catalog.', '2026-01-01T00:00:00Z'),
('perm_payroll_reports_summary_view', 'payroll_reports.summary.view', 'payroll_reports', 'summary_view', 'View monthly payroll summary reports.', '2026-01-01T00:00:00Z'),
('perm_payroll_reports_employee_view', 'payroll_reports.employee.view', 'payroll_reports', 'employee_view', 'View employee payroll detail reports.', '2026-01-01T00:00:00Z'),
('perm_payroll_reports_salary_view', 'payroll_reports.salary.view', 'payroll_reports', 'salary_view', 'View salary and compensation reports.', '2026-01-01T00:00:00Z'),
('perm_payroll_reports_deductions_view', 'payroll_reports.deductions.view', 'payroll_reports', 'deductions_view', 'View payroll deduction reports.', '2026-01-01T00:00:00Z'),
('perm_payroll_reports_advances_view', 'payroll_reports.advances.view', 'payroll_reports', 'advances_view', 'View advance payment reports.', '2026-01-01T00:00:00Z'),
('perm_payroll_reports_loans_view', 'payroll_reports.loans.view', 'payroll_reports', 'loans_view', 'View salary loan reports.', '2026-01-01T00:00:00Z'),
('perm_payroll_reports_attendance_deductions_view', 'payroll_reports.attendance_deductions.view', 'payroll_reports', 'attendance_deductions_view', 'View attendance deduction reports.', '2026-01-01T00:00:00Z'),
('perm_payroll_reports_overtime_view', 'payroll_reports.overtime.view', 'payroll_reports', 'overtime_view', 'View overtime payroll reports.', '2026-01-01T00:00:00Z'),
('perm_payroll_reports_long_leave_view', 'payroll_reports.long_leave.view', 'payroll_reports', 'long_leave_view', 'View long leave deduction reports.', '2026-01-01T00:00:00Z'),
('perm_payroll_reports_leave_deductions_view', 'payroll_reports.leave_deductions.view', 'payroll_reports', 'leave_deductions_view', 'View leave deduction and unpaid leave reports.', '2026-01-01T00:00:00Z'),
('perm_payroll_reports_payslips_view', 'payroll_reports.payslips.view', 'payroll_reports', 'payslips_view', 'View payslip status reports.', '2026-01-01T00:00:00Z'),
('perm_payroll_reports_approvals_view', 'payroll_reports.approvals.view', 'payroll_reports', 'approvals_view', 'View payroll approval and finalization reports.', '2026-01-01T00:00:00Z'),
('perm_payroll_reports_cost_view', 'payroll_reports.cost.view', 'payroll_reports', 'cost_view', 'View outlet and department payroll cost reports.', '2026-01-01T00:00:00Z'),
('perm_payroll_reports_variance_view', 'payroll_reports.variance.view', 'payroll_reports', 'variance_view', 'View payroll variance reports.', '2026-01-01T00:00:00Z'),
('perm_payroll_reports_audit_view', 'payroll_reports.audit.view', 'payroll_reports', 'audit_view', 'View safe payroll audit reports.', '2026-01-01T00:00:00Z'),
('perm_payroll_reports_finance_summary_view', 'payroll_reports.finance_summary.view', 'payroll_reports', 'finance_summary_view', 'View finance-facing payroll summary reports.', '2026-01-01T00:00:00Z'),
('perm_payroll_reports_sensitive_amounts_view', 'payroll_reports.sensitive_amounts.view', 'payroll_reports', 'sensitive_amounts_view', 'View sensitive payroll amounts in reports.', '2026-01-01T00:00:00Z');

INSERT OR IGNORE INTO permissions (id, permission_key, module, action, description, created_at) VALUES
('perm_report_exports_catalog_view', 'report_exports.catalog.view', 'report_exports', 'catalog_view', 'View the report export catalog.', '2026-01-01T00:00:00Z'),
('perm_report_exports_preview', 'report_exports.preview', 'report_exports', 'preview', 'Preview report export columns, redaction, and sample rows.', '2026-01-01T00:00:00Z'),
('perm_report_exports_create', 'report_exports.create', 'report_exports', 'create', 'Create report export jobs.', '2026-01-01T00:00:00Z'),
('perm_report_exports_download', 'report_exports.download', 'report_exports', 'download', 'Download generated report exports.', '2026-01-01T00:00:00Z'),
('perm_report_exports_cancel', 'report_exports.cancel', 'report_exports', 'cancel', 'Cancel pending report export jobs.', '2026-01-01T00:00:00Z'),
('perm_report_exports_history_view', 'report_exports.history.view', 'report_exports', 'history_view', 'View own report export history.', '2026-01-01T00:00:00Z'),
('perm_report_exports_print', 'report_exports.print', 'report_exports', 'print', 'Open print-friendly report views.', '2026-01-01T00:00:00Z'),
('perm_report_exports_sensitive', 'report_exports.sensitive', 'report_exports', 'sensitive', 'Export sensitive report columns when underlying permissions also allow it.', '2026-01-01T00:00:00Z'),
('perm_report_exports_admin_manage', 'report_exports.admin.manage', 'report_exports', 'admin_manage', 'Manage company report export jobs and history.', '2026-01-01T00:00:00Z'),
('perm_report_exports_employee_profile_print', 'report_exports.employee_profile.print', 'report_exports', 'employee_profile_print', 'Print allowed Employee 360 profile sections.', '2026-01-01T00:00:00Z'),
('perm_report_exports_audit_view', 'report_exports.audit.view', 'report_exports', 'audit_view', 'View report export audit history.', '2026-01-01T00:00:00Z');

INSERT OR IGNORE INTO permissions (id, permission_key, module, action, description, created_at) VALUES
('perm_imports_view', 'imports.view', 'imports', 'view', 'View hardened import jobs and history.', '2026-01-01T00:00:00Z'),
('perm_imports_templates_view', 'imports.templates.view', 'imports', 'templates_view', 'View and download import templates.', '2026-01-01T00:00:00Z'),
('perm_imports_upload', 'imports.upload', 'imports', 'upload', 'Create import jobs from CSV content.', '2026-01-01T00:00:00Z'),
('perm_imports_preview', 'imports.preview', 'imports', 'preview', 'Validate and preview import rows without mutating business data.', '2026-01-01T00:00:00Z'),
('perm_imports_apply', 'imports.apply', 'imports', 'apply', 'Apply validated import jobs.', '2026-01-01T00:00:00Z'),
('perm_imports_cancel', 'imports.cancel', 'imports', 'cancel', 'Cancel pending import jobs.', '2026-01-01T00:00:00Z'),
('perm_imports_history_view', 'imports.history.view', 'imports', 'history_view', 'View company import history.', '2026-01-01T00:00:00Z'),
('perm_imports_errors_view', 'imports.errors.view', 'imports', 'errors_view', 'View import row errors.', '2026-01-01T00:00:00Z'),
('perm_imports_employee_manage', 'imports.employee.manage', 'imports', 'employee_manage', 'Import employee master data.', '2026-01-01T00:00:00Z'),
('perm_imports_documents_manage', 'imports.documents.manage', 'imports', 'documents_manage', 'Import employee document metadata.', '2026-01-01T00:00:00Z'),
('perm_imports_leave_balances_manage', 'imports.leave_balances.manage', 'imports', 'leave_balances_manage', 'Import leave balance opening and adjustment rows.', '2026-01-01T00:00:00Z'),
('perm_imports_salary_manage', 'imports.salary.manage', 'imports', 'salary_manage', 'Import salary and compensation rows.', '2026-01-01T00:00:00Z'),
('perm_imports_attendance_manage', 'imports.attendance.manage', 'imports', 'attendance_manage', 'Import attendance rows through the import-safe path.', '2026-01-01T00:00:00Z'),
('perm_imports_holidays_manage', 'imports.holidays.manage', 'imports', 'holidays_manage', 'Import holiday calendar rows.', '2026-01-01T00:00:00Z'),
('perm_imports_assets_manage', 'imports.assets.manage', 'imports', 'assets_manage', 'Import asset and uniform assignment metadata.', '2026-01-01T00:00:00Z'),
('perm_imports_advances_loans_manage', 'imports.advances_loans.manage', 'imports', 'advances_loans_manage', 'Import advances and salary loan rows.', '2026-01-01T00:00:00Z'),
('perm_imports_sensitive_manage', 'imports.sensitive.manage', 'imports', 'sensitive_manage', 'Manage sensitive import previews and applies.', '2026-01-01T00:00:00Z');

INSERT OR IGNORE INTO permissions (id, permission_key, module, action, description, created_at) VALUES
('perm_data_retention_view', 'data_retention.view', 'data_retention', 'view', 'View data retention settings, archive jobs, and archived record summaries.', '2026-01-01T00:00:00Z'),
('perm_data_retention_settings_manage', 'data_retention.settings.manage', 'data_retention', 'settings_manage', 'Manage company-scoped retention and archive-only policy settings.', '2026-01-01T00:00:00Z'),
('perm_data_retention_preview', 'data_retention.preview', 'data_retention', 'preview', 'Preview archive candidates without mutating business data.', '2026-01-01T00:00:00Z'),
('perm_data_retention_archive', 'data_retention.archive', 'data_retention', 'archive', 'Apply approved archive jobs with typed confirmation.', '2026-01-01T00:00:00Z'),
('perm_data_retention_restore', 'data_retention.restore', 'data_retention', 'restore', 'Restore safely restorable records from archive.', '2026-01-01T00:00:00Z'),
('perm_data_retention_cancel_job', 'data_retention.cancel_job', 'data_retention', 'cancel_job', 'Cancel pending or preview-ready archive jobs.', '2026-01-01T00:00:00Z'),
('perm_data_retention_audit_view', 'data_retention.audit.view', 'data_retention', 'audit_view', 'View data retention audit summaries and job history.', '2026-01-01T00:00:00Z'),
('perm_data_retention_purge', 'data_retention.purge', 'data_retention', 'purge', 'Reserved dangerous purge permission; purge remains disabled by default.', '2026-01-01T00:00:00Z');

-- Phase 13A permission audit compatibility aliases. These keep backend,
-- frontend, and service-layer guards seedable without renaming production keys.
INSERT OR IGNORE INTO permissions (id, permission_key, module, action, description, created_at) VALUES
('perm_company_view_alias', 'company.view', 'settings', 'company_view', 'View company information settings.', '2026-01-01T00:00:00Z'),
('perm_company_manage_alias', 'company.manage', 'settings', 'company_manage', 'Manage company information settings.', '2026-01-01T00:00:00Z'),
('perm_attendance_settings_view_alias', 'attendance.settings.view', 'attendance', 'settings_view', 'View attendance settings.', '2026-01-01T00:00:00Z'),
('perm_attendance_override_manual_corrections', 'attendance.override_manual_corrections', 'attendance', 'override_manual_corrections', 'Override import blocking for manually corrected attendance dates.', '2026-01-01T00:00:00Z'),
('perm_backup_settings_view_alias', 'backup.settings.view', 'backup_settings', 'view', 'View backup and recovery settings.', '2026-01-01T00:00:00Z'),
('perm_backup_settings_manage_alias', 'backup.settings.manage', 'backup_settings', 'manage', 'Manage backup and recovery settings.', '2026-01-01T00:00:00Z'),
('perm_devices_settings_view_alias', 'devices.settings.view', 'sync_settings', 'devices_settings_view', 'View device and sync settings.', '2026-01-01T00:00:00Z'),
('perm_devices_settings_manage_alias', 'devices.settings.manage', 'sync_settings', 'devices_settings_manage', 'Manage device and sync settings.', '2026-01-01T00:00:00Z'),
('perm_documents_settings_view_alias', 'documents.settings.view', 'documents_settings', 'view', 'View document settings.', '2026-01-01T00:00:00Z'),
('perm_documents_settings_manage_alias', 'documents.settings.manage', 'documents_settings', 'manage', 'Manage document settings.', '2026-01-01T00:00:00Z'),
('perm_import_export_settings_view_alias', 'import_export.settings.view', 'import_export_settings', 'view', 'View import/export settings.', '2026-01-01T00:00:00Z'),
('perm_import_export_settings_manage_alias', 'import_export.settings.manage', 'import_export_settings', 'manage', 'Manage import/export settings.', '2026-01-01T00:00:00Z'),
('perm_leave_settings_view_alias', 'leave.settings.view', 'leave_settings', 'view', 'View leave settings.', '2026-01-01T00:00:00Z'),
('perm_leave_settings_manage_alias', 'leave.settings.manage', 'leave_settings', 'manage', 'Manage leave settings.', '2026-01-01T00:00:00Z'),
('perm_notifications_settings_view_alias', 'notifications.settings.view', 'notifications', 'settings_view', 'View notification settings.', '2026-01-01T00:00:00Z'),
('perm_notifications_settings_manage_alias', 'notifications.settings.manage', 'notifications', 'settings_manage', 'Manage notification settings.', '2026-01-01T00:00:00Z'),
('perm_reports_settings_view_alias', 'reports.settings.view', 'reports', 'settings_view', 'View report settings.', '2026-01-01T00:00:00Z'),
('perm_reports_settings_manage_alias', 'reports.settings.manage', 'reports', 'settings_manage', 'Manage report settings.', '2026-01-01T00:00:00Z'),
('perm_security_view_alias', 'security.view', 'security_settings', 'view', 'View security settings.', '2026-01-01T00:00:00Z'),
('perm_security_manage_alias', 'security.manage', 'security_settings', 'manage', 'Manage security settings.', '2026-01-01T00:00:00Z'),
('perm_payroll_settings_view_alias', 'payroll.settings.view', 'payroll_settings', 'view', 'View payroll settings.', '2026-01-01T00:00:00Z'),
('perm_payroll_settings_manage_alias', 'payroll.settings.manage', 'payroll_settings', 'manage', 'Manage payroll settings.', '2026-01-01T00:00:00Z'),
('perm_payroll_manage_alias', 'payroll.manage', 'payroll', 'manage', 'Manage payroll setup and employee compensation workflows.', '2026-01-01T00:00:00Z'),
('perm_payroll_process_alias', 'payroll.process', 'payroll', 'process', 'Process payroll and view process-level payroll reporting where allowed.', '2026-01-01T00:00:00Z'),
('perm_payroll_full_access', 'payroll.full_access', 'payroll_admin', 'full_access', 'Explicit company-wide payroll access for trusted payroll administrators.', '2026-01-01T00:00:00Z'),
('perm_employees_manage_alias', 'employees.manage', 'employees', 'manage', 'Manage employee profile lifecycle workflows.', '2026-01-01T00:00:00Z'),
('perm_employees_job_change_manage', 'employees.job_change.manage', 'employees', 'job_change_manage', 'Manage employee job changes.', '2026-01-01T00:00:00Z'),
('perm_employees_job_history_view', 'employees.job_history.view', 'employees', 'job_history_view', 'View employee job history.', '2026-01-01T00:00:00Z'),
('perm_employees_salary_view_alias', 'employees.salary.view', 'employees', 'salary_view', 'View employee salary history where salary permissions allow.', '2026-01-01T00:00:00Z'),
('perm_employees_salary_manage_alias', 'employees.salary.manage', 'employees', 'salary_manage', 'Manage employee salary history where salary permissions allow.', '2026-01-01T00:00:00Z'),
('perm_employees_view_salary_alias', 'employees.view_salary', 'employees', 'view_salary', 'View employee salary information.', '2026-01-01T00:00:00Z'),
('perm_employees_edit_salary_alias', 'employees.edit_salary', 'employees', 'edit_salary', 'Edit employee salary information.', '2026-01-01T00:00:00Z'),
('perm_employees_compensation_view', 'employees.compensation.view', 'employees', 'compensation_view', 'View employee compensation components.', '2026-01-01T00:00:00Z'),
('perm_employees_compensation_manage', 'employees.compensation.manage', 'employees', 'compensation_manage', 'Manage employee compensation components.', '2026-01-01T00:00:00Z'),
('perm_offboarding_view_alias', 'offboarding.view', 'employees', 'offboarding_view_alias', 'View offboarding cases.', '2026-01-01T00:00:00Z'),
('perm_offboarding_manage_alias', 'offboarding.manage', 'employees', 'offboarding_manage_alias', 'Manage offboarding cases.', '2026-01-01T00:00:00Z'),
('perm_offboarding_complete_task_alias', 'offboarding.complete_task', 'employees', 'offboarding_complete_task_alias', 'Complete offboarding tasks.', '2026-01-01T00:00:00Z'),
('perm_offboarding_final_settlement_alias', 'offboarding.final_settlement', 'employees', 'offboarding_final_settlement_alias', 'Prepare offboarding final settlement details.', '2026-01-01T00:00:00Z'),
('perm_rosters_view_alias', 'rosters.view', 'roster', 'view_alias', 'View rosters.', '2026-01-01T00:00:00Z'),
('perm_rosters_manage_alias', 'rosters.manage', 'roster', 'manage_alias', 'Manage rosters.', '2026-01-01T00:00:00Z'),
('perm_rosters_publish_alias', 'rosters.publish', 'roster', 'publish_alias', 'Publish rosters.', '2026-01-01T00:00:00Z'),
('perm_rosters_resolve_conflicts_alias', 'rosters.resolve_conflicts', 'roster', 'resolve_conflicts_alias', 'Resolve roster conflicts.', '2026-01-01T00:00:00Z'),
('perm_shift_templates_view', 'shift_templates.view', 'roster', 'shift_templates_view', 'View shift templates.', '2026-01-01T00:00:00Z'),
('perm_shift_templates_manage', 'shift_templates.manage', 'roster', 'shift_templates_manage', 'Manage shift templates.', '2026-01-01T00:00:00Z'),
('perm_profile_updates_view_alias', 'profile_updates.view', 'profile_update_requests', 'view_alias', 'View profile update requests.', '2026-01-01T00:00:00Z'),
('perm_profile_updates_review_alias', 'profile_updates.review', 'profile_update_requests', 'review_alias', 'Review profile update requests.', '2026-01-01T00:00:00Z');

-- Employee structure foundation permissions. Levels suggest defaults only; roles and
-- permissions remain the final authority for system access.
INSERT OR IGNORE INTO permissions (id, permission_key, module, action, description, created_at) VALUES
('perm_org_departments_view', 'organization.departments.view', 'organization', 'departments_view', 'View organization departments.', '2026-01-01T00:00:00Z'),
('perm_org_departments_manage', 'organization.departments.manage', 'organization', 'departments_manage', 'Manage organization departments.', '2026-01-01T00:00:00Z'),
('perm_org_positions_view', 'organization.positions.view', 'organization', 'positions_view', 'View organization positions and titles.', '2026-01-01T00:00:00Z'),
('perm_org_positions_manage', 'organization.positions.manage', 'organization', 'positions_manage', 'Manage organization positions and titles.', '2026-01-01T00:00:00Z'),
('perm_org_levels_view', 'organization.levels.view', 'organization', 'levels_view', 'View access levels.', '2026-01-01T00:00:00Z'),
('perm_org_levels_manage', 'organization.levels.manage', 'organization', 'levels_manage', 'Manage access level metadata.', '2026-01-01T00:00:00Z'),
('perm_org_level_role_templates_view', 'organization.levelRoleTemplates.view', 'organization', 'level_role_templates_view', 'View level role templates.', '2026-01-01T00:00:00Z'),
('perm_org_level_role_templates_manage', 'organization.levelRoleTemplates.manage', 'organization', 'level_role_templates_manage', 'Manage level role templates.', '2026-01-01T00:00:00Z'),
('perm_employees_structure_view', 'employees.structure.view', 'employees', 'structure_view', 'View employee department, position, and level structure.', '2026-01-01T00:00:00Z'),
('perm_employees_structure_manage', 'employees.structure.manage', 'employees', 'structure_manage', 'Manage employee department, position, and level structure.', '2026-01-01T00:00:00Z');
