import type { ImportTemplate, ImportTemplateColumn, ImportType } from "./imports.types";

const c = (
  key: string,
  label: string,
  required: boolean,
  data_type: ImportTemplateColumn["data_type"],
  example: string,
  description: string,
  options: Partial<ImportTemplateColumn> = {},
): ImportTemplateColumn => ({ key, label, required, data_type, example, description, ...options });

export const IMPORT_TEMPLATES: ImportTemplate[] = [
  {
    import_type: "employee_master",
    name: "Employee Master Import",
    description: "Create or update employee master records with outlet, department, position, and identity context.",
    category: "employees",
    required_permission: "imports.employee.manage",
    sensitive: true,
    supported_modes: ["create_only", "update_only", "upsert", "validate_only"],
    max_rows: 1000,
    columns: [
      c("employee_code", "Employee Code", false, "text", "EMP-001", "Unique employee code. Required for update_only."),
      c("full_name", "Full Name", true, "text", "Aisha Mohamed", "Employee legal or display name."),
      c("employee_type", "Employee Type", true, "enum", "foreign", "Local or foreign employee type.", { accepted_values: ["local", "foreign"] }),
      c("nationality", "Nationality", false, "text", "Maldivian", "Nationality for compliance reporting."),
      c("outlet", "Outlet", true, "text", "Male Outlet", "Outlet ID, code, or name in this company."),
      c("department", "Department", false, "text", "HR", "Department ID, code, or name in this company."),
      c("position", "Position", false, "text", "HR Officer", "Position ID, code, or title in this company."),
      c("join_date", "Join Date", true, "date", "2026-06-01", "Employment join date in YYYY-MM-DD."),
      c("employment_status", "Employment Status", false, "enum", "active", "Current employment status.", { accepted_values: ["active", "inactive", "probation", "terminated", "archived", "resigned"] }),
      c("phone", "Phone", false, "text", "+9607000000", "Contact phone if allowed.", { sensitive: true }),
      c("national_id", "National ID", false, "text", "A000000", "Local identity number where applicable.", { sensitive: true }),
      c("passport_number", "Passport Number", false, "text", "P1234567", "Passport number for foreign employees.", { sensitive: true }),
      c("work_permit_number", "Work Permit Number", false, "text", "WP-123", "Work permit number if available.", { sensitive: true }),
      c("emergency_contact_name", "Emergency Contact Name", false, "text", "Ahmed", "Emergency contact name."),
      c("emergency_contact_phone", "Emergency Contact Phone", false, "text", "+9607111111", "Emergency contact phone.", { sensitive: true }),
      c("emergency_contact_relation", "Emergency Contact Relationship", false, "text", "Parent", "Relationship to emergency contact."),
    ],
  },
  {
    import_type: "employee_documents",
    name: "Employee Document Metadata Import",
    description: "Import document metadata only. Raw files must use the secure document upload flow.",
    category: "documents",
    required_permission: "imports.documents.manage",
    sensitive: true,
    supported_modes: ["create_only", "update_only", "upsert", "validate_only"],
    max_rows: 1000,
    columns: [
      c("employee_code", "Employee Code", true, "text", "EMP-001", "Employee code in this company."),
      c("document_category", "Document Category", true, "text", "passport", "Document category or code."),
      c("document_number", "Document Number", false, "text", "P1234567", "Reference number.", { sensitive: true }),
      c("issue_date", "Issue Date", false, "date", "2024-01-01", "Issue date."),
      c("expiry_date", "Expiry Date", false, "date", "2027-01-01", "Expiry date."),
      c("status", "Status", false, "enum", "valid", "Document status.", { accepted_values: ["valid", "expired", "pending", "missing"] }),
      c("notes", "Notes", false, "text", "Metadata import only", "Safe notes."),
    ],
  },
  {
    import_type: "leave_balances",
    name: "Leave Balance Opening Import",
    description: "Import opening balances or adjustments into the Phase 9A balance ledger.",
    category: "leave",
    required_permission: "imports.leave_balances.manage",
    sensitive: false,
    supported_modes: ["create_only", "update_only", "upsert", "validate_only"],
    max_rows: 1000,
    columns: [
      c("employee_code", "Employee Code", true, "text", "EMP-001", "Employee code."),
      c("leave_type_code", "Leave Type Code", true, "text", "annual", "Leave type key/code."),
      c("policy_year", "Policy Year", true, "number", "2026", "Policy year."),
      c("opening_balance", "Opening Balance", true, "number", "12", "Opening balance days."),
      c("carried_forward", "Carried Forward", false, "number", "2", "Carried-forward days."),
      c("adjustment_reason", "Adjustment Reason", true, "text", "Opening migration", "Reason required for audit and ledger."),
    ],
  },
  {
    import_type: "salary_compensation",
    name: "Salary / Compensation Import",
    description: "Import salary history rows. Sensitive permission and reason are required.",
    category: "payroll",
    required_permission: "imports.salary.manage",
    sensitive: true,
    supported_modes: ["create_only", "validate_only"],
    max_rows: 500,
    columns: [
      c("employee_code", "Employee Code", true, "text", "EMP-001", "Employee code."),
      c("base_salary", "Base Salary", true, "money", "15000", "Monthly salary amount.", { sensitive: true }),
      c("effective_date", "Effective Date", true, "date", "2026-06-01", "Salary effective date."),
      c("reason", "Reason", true, "text", "Approved salary setup", "Reason required."),
      c("status", "Status", false, "enum", "approved", "Salary status.", { accepted_values: ["approved", "pending"] }),
    ],
  },
  {
    import_type: "attendance",
    name: "Attendance Import",
    description: "Import attendance rows through the manual correction-safe path with source=import.",
    category: "attendance",
    required_permission: "imports.attendance.manage",
    sensitive: false,
    supported_modes: ["create_only", "validate_only"],
    max_rows: 1000,
    columns: [
      c("employee_code", "Employee Code", true, "text", "EMP-001", "Employee code."),
      c("attendance_date", "Attendance Date", true, "date", "2026-06-08", "Attendance date."),
      c("check_in_time", "Check-In Time", false, "text", "08:00", "HH:mm or ISO time."),
      c("check_out_time", "Check-Out Time", false, "text", "17:00", "HH:mm or ISO time."),
      c("attendance_status", "Attendance Status", false, "enum", "present", "Attendance status.", { accepted_values: ["present", "absent", "late", "half_day", "holiday", "leave"] }),
      c("reason", "Reason", true, "text", "Legacy import", "Reason required."),
      c("notes", "Notes", false, "text", "Imported from legacy sheet", "Safe notes."),
    ],
  },
  {
    import_type: "holidays",
    name: "Holiday Import",
    description: "Import holiday calendar rows with recurring and applicability flags.",
    category: "holidays",
    required_permission: "imports.holidays.manage",
    sensitive: false,
    supported_modes: ["create_only", "upsert", "validate_only"],
    max_rows: 500,
    columns: [
      c("holiday_name", "Holiday Name", true, "text", "National Day", "Holiday name."),
      c("code", "Code", false, "text", "NATIONAL_DAY", "Optional unique code."),
      c("holiday_type", "Holiday Type", true, "enum", "public_holiday", "Holiday type.", { accepted_values: ["public_holiday", "company_holiday", "outlet_holiday", "optional_holiday", "religious_holiday", "national_holiday", "replacement_holiday", "other"] }),
      c("date", "Date", true, "date", "2026-07-26", "Start date."),
      c("end_date", "End Date", false, "date", "2026-07-27", "End date for multi-day holidays."),
      c("is_recurring", "Recurring", false, "boolean", "true", "Whether holiday repeats yearly."),
      c("outlet", "Outlet", false, "text", "Male Outlet", "Outlet ID/name where applicable."),
      c("applies_to_local_employees", "Applies To Local", false, "boolean", "true", "Local employee applicability."),
      c("applies_to_foreign_employees", "Applies To Foreign", false, "boolean", "true", "Foreign employee applicability."),
      c("paid_holiday", "Paid Holiday", false, "boolean", "true", "Paid holiday flag."),
      c("affects_leave_duration", "Affects Leave", false, "boolean", "true", "Affects leave duration."),
      c("affects_attendance_absence", "Affects Attendance", false, "boolean", "true", "Excuses attendance absence."),
      c("affects_long_leave_payroll", "Affects Long Leave Payroll", false, "boolean", "true", "Affects long-leave payroll."),
      c("reason", "Reason", true, "text", "Calendar import", "Reason required."),
    ],
  },
  {
    import_type: "assets_uniforms",
    name: "Asset / Uniform Assignment Import",
    description: "Import assignment metadata for assets and uniforms where the module exists.",
    category: "assets",
    required_permission: "imports.assets.manage",
    sensitive: false,
    supported_modes: ["create_only", "upsert", "validate_only"],
    max_rows: 1000,
    columns: [
      c("employee_code", "Employee Code", true, "text", "EMP-001", "Employee code."),
      c("item_type", "Item Type", true, "enum", "asset", "Asset or uniform.", { accepted_values: ["asset", "uniform"] }),
      c("item_code", "Item Code", true, "text", "LAP-001", "Asset/uniform code."),
      c("item_name", "Item Name", false, "text", "Laptop", "Item name."),
      c("assigned_date", "Assigned Date", true, "date", "2026-06-08", "Assigned date."),
      c("due_date", "Due Date", false, "date", "2026-12-31", "Due/return date."),
      c("condition", "Condition", false, "text", "good", "Condition."),
      c("status", "Status", false, "text", "assigned", "Assignment status."),
      c("notes", "Notes", false, "text", "Issued during onboarding", "Safe notes."),
    ],
  },
  {
    import_type: "advances_loans",
    name: "Advances / Salary Loans Import",
    description: "Import advance or salary loan records only when payroll permission allows it.",
    category: "payroll",
    required_permission: "imports.advances_loans.manage",
    sensitive: true,
    supported_modes: ["create_only", "validate_only"],
    max_rows: 500,
    columns: [
      c("employee_code", "Employee Code", true, "text", "EMP-001", "Employee code."),
      c("record_type", "Record Type", true, "enum", "advance", "Advance or salary loan.", { accepted_values: ["advance", "loan"] }),
      c("amount", "Amount", true, "money", "5000", "Amount.", { sensitive: true }),
      c("date", "Date", true, "date", "2026-06-08", "Payment/start date."),
      c("installment_amount", "Installment Amount", false, "money", "1000", "Installment for loans.", { sensitive: true }),
      c("payroll_month", "Payroll Month", false, "text", "2026-07", "Deduction/payroll month."),
      c("status", "Status", false, "text", "pending", "Record status."),
      c("reason", "Reason", true, "text", "Approved import", "Reason required."),
    ],
  },
];

export const getTemplate = (importType: string) =>
  IMPORT_TEMPLATES.find((template) => template.import_type === importType as ImportType) ?? null;
