import { api } from "@/lib/api-client";
import { buildQueryString } from "@/lib/query-string";
import type {
  LeaveAccrualPayload,
  LeaveAccrualResult,
  LeaveApprovalDetail,
  LeaveBalance,
  LeaveBalanceAdjustPayload,
  LeaveBalanceTransaction,
  LeaveCarryForwardPayload,
  LeaveExpiryPayload,
  LeaveFilters,
  LeaveDelegatePayload,
  LeaveOpeningBalancePayload,
  LeavePolicy,
  LeaveRequest,
  LeaveRequestPayload,
  LeaveType,
  LeaveTypeUpdatePayload,
} from "./leave.types";

export const leaveApi = {
  listRequests: (filters: LeaveFilters = {}) => api.get<LeaveRequest[]>(`/leave/requests${buildQueryString(filters)}`),
  listApprovalInbox: (filters: LeaveFilters = {}) => api.get<LeaveRequest[]>(`/leave/approvals/inbox${buildQueryString(filters)}`),
  listApprovalHistory: (filters: LeaveFilters = {}) => api.get<LeaveRequest[]>(`/leave/approvals/history${buildQueryString(filters)}`),
  getApprovalDetail: (id: string) => api.get<LeaveApprovalDetail>(`/leave/approvals/${id}`),
  getTimeline: (id: string) => api.get<LeaveApprovalDetail>(`/leave/requests/${id}/timeline`),
  getRequest: (id: string) => api.get<{ leave_request: LeaveRequest }>(`/leave/requests/${id}`),
  createRequest: (payload: LeaveRequestPayload) => api.post<{ leave_request?: LeaveRequest; long_leave_required?: boolean }>("/leave/requests", payload),
  updateRequest: (id: string, payload: Partial<LeaveRequestPayload>) => api.patch<{ leave_request?: LeaveRequest }>(`/leave/requests/${id}`, payload),
  approveRequest: (id: string, reason: string) => api.post<{ approved: boolean }>(`/leave/requests/${id}/approve`, { reason }),
  rejectRequest: (id: string, reason: string) => api.post<{ rejected: boolean }>(`/leave/requests/${id}/reject`, { reason }),
  cancelRequest: (id: string, reason: string) => api.post<{ cancelled: boolean }>(`/leave/requests/${id}/cancel`, { reason }),
  withdrawRequest: (id: string, reason: string) => api.post<{ withdrawn: boolean }>(`/leave/requests/${id}/withdraw`, { reason }),
  delegateRequest: (id: string, payload: LeaveDelegatePayload) => api.post<{ delegated: boolean }>(`/leave/requests/${id}/delegate`, payload),
  escalateRequest: (id: string, reason: string) => api.post<{ escalated: boolean }>(`/leave/requests/${id}/escalate`, { reason }),
  listBalances: (filters: LeaveFilters = {}) => api.get<LeaveBalance[]>(`/leave/balances${buildQueryString(filters)}`),
  adjustBalance: (employeeId: string, payload: LeaveBalanceAdjustPayload) => api.post<{ updated: boolean }>(`/leave/balances/${employeeId}/adjust`, payload),
  setOpeningBalance: (payload: LeaveOpeningBalancePayload) => api.post<{ balance: LeaveBalance }>("/leave/balances/opening", payload),
  carryForwardBalance: (payload: LeaveCarryForwardPayload) => api.post<{ balance?: LeaveBalance }>("/leave/balances/carry-forward", payload),
  expireBalance: (payload: LeaveExpiryPayload) => api.post<{ balance?: LeaveBalance }>("/leave/balances/expire", payload),
  rebuildBalance: (employeeId: string, year: number, reason: string) => api.post<{ rebuilt: boolean }>(`/leave/balances/${employeeId}/rebuild?year=${encodeURIComponent(String(year))}`, { reason }),
  listBalanceTransactions: (employeeId: string, filters: LeaveFilters = {}) => api.get<LeaveBalanceTransaction[]>(`/leave/balances/${employeeId}/transactions${buildQueryString(filters)}`),
  previewAccrual: (payload: LeaveAccrualPayload) => api.post<LeaveAccrualResult>("/leave/accrual/preview", payload),
  applyAccrual: (payload: LeaveAccrualPayload) => api.post<LeaveAccrualResult>("/leave/accrual/apply", payload),
  listTypes: (filters: LeaveFilters = {}) => api.get<LeaveType[]>(`/leave/types${buildQueryString(filters)}`),
  updateType: (id: string, payload: LeaveTypeUpdatePayload) => api.patch<{ updated: boolean }>(`/leave/types/${id}`, payload),
  listPolicies: (filters: LeaveFilters = {}) => api.get<LeavePolicy[]>(`/leave/policies${buildQueryString(filters)}`),
  calendar: (filters: LeaveFilters = {}) => api.get<{ calendar: LeaveRequest[] }>(`/leave/calendar${buildQueryString(filters)}`),
};
